- Makefile
- lib/backend/docker.go
- lib/backend/jupiterbrain.go
- lib/backend/package.go
- lib/backend/sauce_labs.go
- lib/job_queue.go
- lib/metrics/package.go
- lib/step_upload_script.go
however improbable it may be.  Testing for this alone is not exhaustive, but
leaves the door open for a use case where the VM/machine is recycled.
> Exit early if build.sh already exists

- src/github.com/travis-ci/worker/backend/docker.go
The old loop seems to have gone from len(cpuSets) to 1, which seems like an off-by-one error (I think it should've gone from len(cpuSets)-1 to 0). I couldn't see a reason for the loop to go backwards, so I changed the loop to go from 0 to len(cpuSets)-1 in order to use the more standard Go loop.
/cc @meatballhat, who wrote the original loop (main question: any reason to go through the slice in reverse?)
> docker: fix a panic by reversing a loop

- utils/pkg/pkg_run
Redoing version checking logic to skip package building earlier in the build when a new version doesn't exist yet
> Redoing version checking logic to skip package building earlier

- src/github.com/travis-ci/worker/cmd/travis-worker/main.go
This is needed before we can use this on EC2-Docker.
> Add support for lifecycle hook

- src/github.com/travis-ci/worker/job.go
- src/github.com/travis-ci/worker/processor.go
These timeouts come from hub and are used in certain cases. This is more work to get to feature parity with the Ruby worker.
> Add support for per-job configurable timeouts in payload

- src/github.com/travis-ci/worker/amqp_job.go
- src/github.com/travis-ci/worker/build_script_generator.go
- src/github.com/travis-ci/worker/canceller.go
- src/github.com/travis-ci/worker/job_queue.go
- src/github.com/travis-ci/worker/log_writer.go
- src/github.com/travis-ci/worker/step_generate_script.go
- src/github.com/travis-ci/worker/step_run_script.go
- src/github.com/travis-ci/worker/step_start_instance.go
- src/github.com/travis-ci/worker/step_subscribe_cancellation.go
- src/github.com/travis-ci/worker/step_update_state.go
- src/github.com/travis-ci/worker/step_upload_script.go
- src/github.com/travis-ci/worker/version.go
This fixes all errors reported by `gometalinter` except:
- "Should have comment or be unexported"
- `errcheck` warnings on `defer`-ed calls
> Fix lint errors

- src/github.com/travis-ci/worker/backend/bluebox.go
- src/github.com/travis-ci/worker/backend/bluebox_test.go
- src/github.com/travis-ci/worker/backend/docker.go
- src/github.com/travis-ci/worker/backend/fake.go
- src/github.com/travis-ci/worker/backend/jupiterbrain.go
- src/github.com/travis-ci/worker/backend/package.go
- src/github.com/travis-ci/worker/canceller.go
- src/github.com/travis-ci/worker/cmd/travis-worker/main.go
- src/github.com/travis-ci/worker/config/config.go
- src/github.com/travis-ci/worker/config/flags.go
- src/github.com/travis-ci/worker/config/help.go
- src/github.com/travis-ci/worker/config/provider_config.go
- src/github.com/travis-ci/worker/context/package.go
- src/github.com/travis-ci/worker/job.go
- src/github.com/travis-ci/worker/log_writer.go
- src/github.com/travis-ci/worker/processor_pool.go
Nothing in this pull request should change any behavior.
The largest change is probably the change in the `backend` package of making all implementations of `backend.Provider` and `backend.Instance` unexported. I did this as I found myself documenting all of the functions on these types as just `Start implements Provider.Start`, or something similar, and realised that the types don't really need to be exported at all, so they probably shouldn't.
My linter still reports some issues, but they are all either "cyclomatic complexity" issues, "duplicated code" issues or "error unchecked issues", all of which could only really be fixed by changing behavior, and not all of them _should_ be fixed, so I'm leaving that for another time.
(Also, this means that every exported type and function now has …
> Fix more lint warnings/errors

- src/github.com/travis-ci/worker/cmd/travis-worker/main.go
- src/github.com/travis-ci/worker/metrics/memstats.go
This includes metrics on things like GC pause times. The metric calculation comes from http://pythonic.zoomquiet.io/data/20131112090955/index.html, but I'm not 100% sure I got everything translated correctly.
> metrics: add Memstats runtime metrics

- utils/pkg/pkg_run
- Detects if a package already exists on package cloud
- If the package exists and is a dev build, it removes it
and publishes it again
- If the package exists and is a release build, it prompts
for manual conflict resolution and the build fails
- This all works on a per package (distro + distro release + type) basis
> Improved package publishing detection and handling

- src/github.com/travis-ci/worker/step_run_script.go
It was including the hard timeout instead of the log timeout. Since the log timeout is usually much shorter than the hard timeout, this could lead to some confusing error messages.
Fixes #49.
> step/run-script: fix log timeout error message

- src/github.com/travis-ci/worker/config/flags.go
This makes it easier to set up Librato in places where it's hard to set per-host settings (such as with our current Chef recipe).
> config: use hostname as default value for librato source

- src/github.com/travis-ci/worker/log_writer.go
We've been seeing an issue where it seems like the output from the logs of a job suddenly stop, and eventually triggers the log timeout. This has happened on several platforms, including multiple OS-es (both Linux and OS X), which leads me to believe the issue is in the worker.
While running some tests that sent a lot of output to the log writer, I noticed that it was possible to get it into a locked state where the flushing would take a long time and therefore Write() would stall on attempting to lock the mutex. This change fixes that so even with a very fast writer, nothing would lock (until you hit the maximum log limit).
While I'm not positive that this will fix the issue we're seeing, it does seem like a good idea to keep the mutex locked for as little time as possible.
> log-writer: lock the mutex as little as possible

- src/github.com/travis-ci/worker/backend/gce.go
The language tag is invalid for some languages (such as "c++"), since a tag can't end with a -. Instead of somehow changing the tags to be valid, I removed the language tag, since I'm not sure why it's useful.
> gce: remove the language tag on instances

- src/github.com/travis-ci/worker/processor.go
If more than one case branch in a select statement can proceed, one is picked at random, which I think is the cause for graceful and forceful shutdown not to work a lot of times.
> processor: check if we're shutting down before picking up job

- src/github.com/travis-ci/worker/processor.go
Previously we pulled the _job_ UUID out of the context (it's an empty string) and set that as the processor UUID, blanking out the UUID from the ProcessorPool.
> processor: assign the right UUID to the processor field in logs

- src/github.com/travis-ci/worker/processor.go
The `graceful` channel isn't buffered, so sending to it will block until
the processor is shut down. Calling `GracefulShutdown()` again will block
forever. Closing the channel will return immediately.
This should fix the issue with graceful shutdowns, since the processor pool waits for `GracefulShutdown()` to return before moving on to the next processor.
> Fix graceful shutdown, mark π

- src/github.com/travis-ci/worker/backend/jupiterbrain.go
I noticed a panic due to `resp` being `nil` and `resp.Body` then throwing a "nil pointer error".
> jupiterbrain: don't panic if an error is returned on Stop

- src/github.com/travis-ci/worker/backend/jupiterbrain.go
Included are a few changes to the Jupiter Brain log writer setup to attempt to fix the issue where the end of the logs aren't being sent to travis-logs. I'm not 100% confident that this will fix it, since these bugs would be in the GCE backend too, but the bug doesn't seem to be there from what I can see.
> Attempt to fix cutoff logs

- image/api_selector.go
- image/api_selector_test.go
We're not doing any kind of separation by language for OS X images, so having to list every language can be error-prone due to missing things. Instead, let's just filter by os:osx, which gets us what we need today.
> image: ignore language for osx_image queries

- amqp_job.go
The finish event can be sent without the received or started event having been sent if something errors in between. In that case, we would send 0001-01-01T00:00:00Z for received_at and/or started_at, causing hub to think the job had ran for roughly 2015 years.
> Don't send zero timestamps in "finished" event to hub

- backend/gce.go
including:
* creating zone operation call once per boot/delete polling loop
* sleeping a configurable amount at the beginning of the boot polling loop
> Perf improvements to GCE backend

- step_run_script.go
Without this, the job ends up being requeued infinitely.
> Mark the job as errored if it goes past the max log length

- amqp_job.go
- backend/gce.go
- metrics/package.go
This rate limiter makes sure that we self-throttle on the number of API calls we make to the GCE API.
> gce: Add rate limiting

- cli.go
- vendor/manifest
Updates to github.com/mihasya/go-metrics-librato since the librato provider in rcrowley/go-metrics has been deprecated for a while, and also sends more percentiles to Librato. More specifically, it sends these:
- 50th %ile (median)
- 75th %ile
- 90th %ile
- 95th %ile
- 99th %ile
- 99.9th %ile
- 100th %ile (maximum)
> Metrics update

- amqp_job_queue.go
- backend/gce.go
- backend/start_attributes.go
- backend/start_attributes_test.go
- file_job_queue.go
- job.go
With this, the `vm_type` field on the payload we get from AMQP can be set to `premium` to get an `n1-standard-4` instead of `n1-standard-2`.
> gce: add support for a premium instance type

- backend/docker.go
While not documented anywhere, in Docker 1.6.0 the resource limits were
moved to HostConfig instead of Config.
BREAKING CHANGES:
- Drops support for Docker versions before 1.6.0 (1.6.0+ is supported) (maybe?)
> docker: pass resource limitations in HostConfig

- backend/docker.go
- backend/docker_test.go
The previous implementation would select the first image that matches any of the tags, but this will go through the tags in order.
> docker: Priorizite language tags over default image

- .travis.yml
- backend/docker.go
- backend/fake.go
- backend/gce.go
- backend/gce_test.go
- backend/jupiterbrain.go
- backend/local.go
- backend/package.go
- cli.go
- context/package.go
- ratelimit/ratelimit.go
- ratelimit/ratelimit_test.go
- vendor/manifest
This allows the rate limiter to share state across all workers, instead of just being local to a single worker process.
I tested this using a load testing script that ran three parallel processes, each spawning 50 goroutines that shared a rate limiter instance set to maximum 40 requests per second, and each goroutine continuously sending requests to a HTTP endpoint which tracked the maximum number of requests it got in a second. I let them run for about 15 minutes, and never did it go over 40 requests in a single second.
I also checked Redis to make sure the keys were actually cleaned up, and all of them expired and got removed correctly.
This could probably be improved in the future by using an implementation that allows you to spike over n req/s for a limited amount of time, as long as …
> Add a Redis-backed rate limiter for GCE

- .travis.yml
Only build packages when the API TOKEN is present as an environment variable. This helps with external PRs building.
> Only build packages when the API TOKEN is present as an environment variable

- step_run_script.go
This PR fixes a misspelling of "maximum" in the messages you get when a build job times out or hits the log quota.
> fix 'maxmimum' spelling in output message

- cli.go
- config/config.go
- config/config_test.go
This pulls in #155 and also adds a way to add a certificate by path, and rebases against latest master.
> #155 (custom AMQP TLS CA) + improvements

- utils/package
Instead of trying to detect if we are building a tag, just use the `$TRAVIS_TAG` var, which should only be set in that case.
> Prevent race condition when pushing to master and creating a tag shotly after

- backend/gce.go
- backend/start_attributes.go
- processor.go
- processor_test.go
It's possible that the job has an extended timeout, and if we are still using the global default for when the worker shuts down, it'll cause an infinite loop until the job is cancelled.
> backend/gce: use hard timeout for the job instead of a global setting

- utils/package-overlay.d/rpm/lib/systemd/system/travis-worker.service
`EnvironmentFile`s aren't "executed", and since we depend on that in order to have certain variables be defined by using others, we can't use them. Changed to a `/bin/sh -c ''` style command instead in `ExecStart`, similar to the upstart file.
In addition, the binary name in `Exec*` needs to be a full path, so `/bin/mkdir` instead of just `mkdir`, for example.
> Fix systemd service file

- utils/package-overlay.d/rpm/lib/systemd/system/travis-worker.service
`%n` expands to `travis-worker.service`, not `travis-worker`. There's probably something else that expands to  `travis-worker`, but it's easier to just hardcode it for now.
> systemd service file: switch %n to travis-worker

- amqp_job_queue.go
The channel object is very long and doesn't contain any exported information that has helped in debugging in the past, so let's remove it to make the log messages easier to read.
> amqp-job-queue: don't log the channel when close fails

- utils/smoke-package
The build is currently failing (I think) because the preinstalled Docker version is now 1.12.0 instead of 1.9.1. This PR just updates what version it expects, I'm hoping that's all that's needed.
@meatballhat or @solarce Do you know if this is correct, or if we specifically want to test against 1.9.1?
> Expect Docker 1.12.0 instead of 1.9.1 to be preinstalled

- CHANGELOG.md
- step_run_script.go
This PR adds a new line with a link to the docs explaining travis_wait when there's a log timeout error :)
> add link to docs when there's a log timeout error

- backend/gce.go
to point to sugilite instead of mega
> Bump GCE backend image default

- backend/jupiterbrain.go
If Jupiter Brain sends a non-200 response code we are leaking HTTP connections.
> backend/jupiterbrain: always close the HTTP body

- backend/jupiterbrain.go
- vendor/manifest
This uses github.com/pkg/errors a lot to provide some context for all errors, which makes it easier for us to figure out exactly where an error comes from when we see an error in the logs, instead of just "file not found" or "EOF".
> backend/jupiterbrain: add context to all errors

- step_start_instance.go
The previous change caused the error to be logged twice, and breaks the
"constant" msg field.
This reverts commit 4ce7d2cfc42e536043277e8257823dd2c7cd32b6.
> Revert "attempt to log upstream error on start failure"

- processor.go
There are many different exit paths out of the Run function, and not all of them marked the "current status" as done as they should. Moving the set to a deferred function should ensure that the processor is always marked as done.
> processor: always mark as done when Run finishes

- step_run_script.go
- step_upload_script.go
Since we've started to wrap the errors using `errors.Wrap` the error returned is no longer the value we expect, which means things like handling max log length overruns don't work right and now requeue the job instead. `errors.Cause` returns the original error, which we can then
compare against.
> Use errors.Cause when checking error values

- backend/cloudbrain.go
- backend/docker.go
- backend/gce.go
- backend/jupiterbrain.go
- ssh/package.go
Instead of loading, parsing and decrypting the key on every SSH connect, this does it only once when the worker is first set up.
Gonna test this in staging once the build passes and I have a binary to test with.
Fixes #206.
> backend/jupiterbrain: parse SSH key on backend init

- log_writer.go
After more discussion, we've decided to leave it at half a second.
This reverts commit 0805aaacce44ac58a3843f3320e4ec98b8c1a67a.
/cc @joshk @solarce
> Revert "Increase the log writer tick to 2 seconds (#156)"

- amqp_job_queue.go
This adds a log message immediately after JSON decode in order to help detect when a worker receives a job (this is the earliest possible point we have the job ID).
It also changes the way the `buildJob` struct is passed to the processor to interrupt that blocking call if the context is cancelled. I suspect this is where some jobs might be getting stuck right now.
> Lost AMQP delivery fixes

- backend/jupiterbrain.go
Mainly:
- Split the "wait for SSH to come up" loop into two separate functions"
- Move HTTP API things to a separate type
The general goal here was to make the functions smaller and easier to read (they used to be bigger than what could fit on my screen, which I think is too big for it to be easy to keep track of what's going on).
> Some Jupiter Brain backend refactoring

- context/package.go
- step_open_log_writer.go
- step_run_script.go
- step_start_instance.go
- step_subscribe_cancellation.go
- step_upload_script.go
Currently we are only tracking very few errors in sentry. This change will give us a 1:1 mapping between requeues and errors in sentry. Allowing us to see diagnostic information like stack traces, error aggregation, error counts, which should help us in keeping track of which errors cause requeues.
> Capture every requeue and send the error to sentry

- errors/errors.go
- image/api_selector.go
- image/api_selector_test.go
- step_start_instance.go
When .travis.yml contains trailing commas, those commas propagate all
the way through to to worker, which builds them into tags and passes
those tags on to job-board.
job-board does not like tags with commas and returns a 500, which then
causes a retry loop.
This patch adds a clearer error message for when that happens, displays
this error message to the user, and also makes sure we do not requeue.
> check tagsets for trailing commas before querying job-board

- amqp_canceller.go
Currently most of the lines in the log look like this:
```
time="2017-01-11T13:53:59Z" level=info msg="no job with this ID found on this worker" command="cancel_job" component=canceller job=123456789 pid=12345
```
This is very noisy makes it difficult to see actual signal in the logs. By changing the log level to `debug` it should no longer show up all the time.
> Change verbosity of canceller missing job id to debug, make logs less spammy

- amqp_job.go
- job.go
- job_test.go
This patch will give us a metric of the actual queue wait time experienced by users.
Depends on https://github.com/travis-ci/travis-scheduler/pull/55
> track queue time via queued_at field from payload

- processor.go
- step_open_log_writer.go
- step_open_log_writer_test.go
- step_start_log_timer.go
- step_write_worker_info.go
- step_write_worker_info_test.go
We are currently experiencing panic()s because stepStartInstance may try to
write a message out to the user, but the log writer has not been initialized
yet.
This patch moves the opening of the log writer further back in time.
> processor: open log writer before startInstance step, so it can write logs to the user

- .editorconfig
I find the 2-space width makes it hard to see what level of indentation are in in the diff views on GitHub Pull Requests, especially since the first level of indentation ends up being just one space due to some bug(?) in how GitHub renders tabs in diffs.
> Increase tab width to 4 spaces

- backend/docker.go
The actual default is defined later to be 64 * 1024 * 1024 bytes:
``` Go
shm := uint64(1024 * 1024 * 64)
```
If it's overriden with SHM, say by saying `SHM=64MB` (which previously was indicated to be the default in the help text, it would go through `humanize.ParseBytes`:
``` Go
if cfg.IsSet("SHM") {
if parsedShm, err := humanize.ParseBytes(cfg.Get("SHM")); err == nil {
shm = parsedShm
}
}
````
`humanize.ParseBytes("64MB")` returns 64 * 1000 * 1000, not 64 * 1024 * 1024, so if you specify `SHM=64MB` you get something other than the default of "64MB". By changing the default in the docs text to "64MiB", the docs default reflects the actual default, as you could pass `SHM=64MiB` and get the same value as the default.
Note that Docker parses numbers differently, so if you pass `--shm=64MB` …
> backend/docker: change SHM default to 64 MiB

- cli.go
Sentry includes the version number on the website if its set, so with this we can see what version of worker is generating which errors.
> Send the version string to Sentry

- CHANGELOG.md
This adds back the links that I messed up in the 2.7.0 release (I only just learned that the brackets in the headers were meant to be links, I always thought it looked a bit weird).
Also adds a link to [Keep a Changelog](http://keepachangelog.com/), since that's the format we've based the changelog on, and adds the "standard" sub-sections to the unreleased header.
> Minor changelog fixes

- .travis.yml
- Makefile
Disables tests without race detection, and changes the Makefile a bit to make sure that `gvt rebuild` is re-run if the manifest has updated since  the last time it was run.
> Speed up Travis CI builds & re-fetch deps when manifest updates

- amqp_job.go
This allows us to more easily track how many jobs are finishing on each worker, instead of having to sum the different state metrics.
> amqp-job: add metric for job finishing without state

- .travis.yml
- vendor/manifest
This pulls in a fix for golang/go#18861.
Fixes #290.
> build: update golang.org/x/crypto/ssh

- amqp_job_queue.go
When the channel is closed, `delivery` would have the zero value, which would fail JSON parsing (since the body is empty), and then panic on `Nack`.
> Fix panic occuring when AMQP delivery channel is closed

- amqp_job.go
- amqp_job_queue.go
- job.go
This counter helps Hub reorder the messages if they arrive in a different order than Worker sent them in, which sometimes causes a "requeue" immediately after "received" to be interpreted as "requeue" and _then_ "receive", causing the job to get stuck.
/cc @svenfuchs, is this roughly what you thought in terms of JSON payloads? I.e. `state_update_count` in the top-level of both the payload from Scheduler and the payload to Hub?
/cc @solarce
> amqp-job: implement state message counter

- backend/docker.go
- backend/package.go
> Merging from grooverdan/worker patch-1

- backend/package.go
This fixes an issue with the docker backend, which is currently unusable due to every container start request returning a 500 from the docker API.
> Ensure str2map does not populate empty keys

- .gitignore
- Makefile
- http_log_part_sink.go
- http_log_part_sink_test.go
- http_log_writer.go
- http_log_writer_test.go
- package_test.go
mostly to cut down a bit on the bulk number of HTTP requests.  I'm guessing that we may want the max batch size to be configurable (?).  **NOTE**: I couldn't find where or how the http log part `UUID` was being used, which is why I dropped it.
**Update**: This solution explicitly _does not_ increase the size of a given log part because there is a max size restriction imposed by Pusher.  Further explanation is available [here](https://github.com/travis-ci/worker/blob/51222dac0393503fc5a28657e2997273e56d6ca1/log_writer.go#L14-L32)! :heart:
> Batch together HTTP log parts writes

- CHANGELOG.md
- http_job_queue.go
and fetch the full jobs in series rather than async goroutine parallel
to help with smoothing out HTTP traffic and avoid goroutine leakage
issues.
> Check for context cancellation every loop in http-job-queue

- cli.go
- config/config.go
- processor.go
- processor_pool.go
- processor_test.go
- step_transform_build_json.go
- step_transform_build_json_test.go
At our company (Schibsted) we are using this feature to inject variables into the Travis build environment:
This way we can have environment variables (i.e secrets) that are common to the whole company.
To do so, we have an external script that once configured in the worker config parameter `FILTER_JOB_JSON_SCRIPT`, will receive via stdin for each job started, the build json. In this json we inject the variables in the `env_vars` section of the json and return the json via stdout. This way the injected variables will appear in the log (and the build environment) as if they was defined in the settings ui.
We developed this feature due to a requirement of our workflow, feel free to close it if you think that is out of scope of your plans for the worker.
> Add step to transform build json using an external filter script

- package/functions.bash
This patch is for fixing a bug in version handling that happens since version `v2.10.0`. Before the patch the output of `git tag -l` is:
```
[...]
v2.1.0
v2.10.0
v2.2.0
v2.3.0
v2.3.1
[...]
v2.9.1
v2.9.2
v2.9.3
```
So it always takes version `v2.9.3` as the last version.
> Sort version tags properly

- http_job.go
- http_log_part_sink.go
so that Sinatra/Rack don't try to parse the body as URI params
> Ensure request Content-Type: application/json

- http_job.go
- http_job_queue.go
- http_log_part_sink.go
to prevent file descriptor leakage.
> Ensure HTTP response bodies are closed in more places

- http_log_part_sink.go
- http_log_writer.go
- http_log_writer_test.go
now that log parts from all processors are buffered together in the log
part sink.
> Remove redundant buffering layer in HTTP log handling

- backend/openstack.go
This commit replaces keystoneApiVersion for the version suggested
by golint, keystoneAPIVersion. This is a cosmetic change.
Signed-off-by: Rafael Peria de Sene <rpsene@br.ibm.com>
> Replace the var name keystoneApiVersion for keystoneAPIVersion

- amqp_canceller.go
- amqp_job.go
- amqp_job_queue.go
- amqp_job_test.go
- amqp_log_writer.go
- cli.go
- context/package.go
- file_job.go
- file_job_queue.go
- http_job.go
- http_job_queue.go
- http_job_queue_test.go
- http_job_test.go
- http_log_writer.go
- job.go
- job_queue.go
- multi_source_job_queue.go
- multi_source_job_queue_test.go
- package_test.go
- processor.go
- processor_pool.go
- step_send_received.go
- step_sleep.go
- step_update_state.go
See #353
I decided to change the relationship between individual processors and job-board so that claims and delivery are handled at the processor level rather than being batched together through a shared job queue.  This is very similar to the way the AMQP job queue works.
I would like to deploy this to AWS staging with queue type of `amqp,http`.
> Send to job queue only when ready

- .github/PULL_REQUEST_TEMPLATE.md
- PULL_REQUEST_TEMPLATE
I have been modifying the current PR template every time so that the ordered list is headers, and this file path is also supported, and with an `.md` extension, too!
> Move the PR template into `.github/`

- CHANGELOG.md
The size of the diff between the last release and master.
I've chosen v3.0.0 because of the breaking changes to the public APIs of `type Job interface` and `func NewHTTPJobQueue`.
I've tested this version in AWS staging, fwiw.  I'd love to hear from anyone running a Travis Enterprise setup, too :grin:.
Is v3.0.0 a good choice, or should I go to v2.12.0, and if so why?
> Prepare for v3.0.0

- backend/openstack.go
As per current implementation of Openstack backend , authentication with the Keystone (identity service) happens at the very start of the worker . However, token generated by Identity Service may expire based on the Openstack configuration settings at Setup level. Once the token expires we cannot perform any API calls. Changes in this PR tries to overcome this issue by allowing automatic re authentication. 
Tested with a local Openstack cloud setup
> Allows to re-authenticate automatically with Openstack identity service if/when token expires.

- multi_source_job_queue.go
The production rollout of v3.0.0 on GCE seems to have introduced this panic:
```
travis-worker: panic: runtime error: invalid memory address or nil pointer dereference 
travis-worker: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa82dfc] 
travis-worker: goroutine 210 [running]: 
travis-worker: github.com/travis-ci/worker.(*MultiSourceJobQueue).Jobs.func1(0xc420163ef0,0xc42000c4e0,0xc420631320, 0x1053520, 0xc4201c0880) 
travis-worker:     /home/travis/gopath/src/github.com/travis-ci/worker/multi_source_job_queue.go:59 +0x30c 
travis-worker: created by github.com/travis-ci/worker.(*MultiSourceJobQueue).Jobs 
travis-worker:     /home/travis/gopath/src/github.com/travis-ci/worker/multi_source_job_queue.go:79 +0x5b9 
```
I decided to check for `nil`, and if so, log and …
> Handle nil incoming job in multi-source job queue

- CHANGELOG.md
- backend/docker.go
CPU sets aren't properly allocated to containers, meaning that some jobs use more than their share of CPUs.
I think this is a problem:
```
cpuSets, err := p.checkoutCPUSets()
if err != nil && cpuSets != "" {
return nil, err
}
```
because if the `checkoutCPUSets` func returns an error, the other value is always an empty string:
```
func (p *dockerProvider) checkoutCPUSets() (string, error) {
[...]
if len(cpuSets) != p.runCPUs {
return "", fmt.Errorf("not enough free CPUsets")
}
```
so `if err != nil && cpuSets != ""` will never be true, so the error is never caught (and in that case, containers are allocated the same CPU set as the host).
Create some sample JSON payloads and put them in `10-created.d/`:
```
$ pwd
/home/aj/git/travis/worker/builds.ec2
$ ls -la
total 60
drwxr-xr-x  7 aj aj …
```
> Properly allocate CPU sets to containers

- .travis.yml
- Dockerfile
This change is so we can continue pushing to packagecloud.io while pushing branches to [travisci/worker-testing](https://hub.docker.com/r/travisci/worker-testing) on Docker Hub.
> Add docker-build smoke-docker docker-push smoke-package back to .travis.yml

- cli.go
Occasionally `travis-worker` will be in the `stop/waiting` state. This PR is intended to make it more obvious when this happens due to a signal.
For example, `SIGWINCH`--window size change--is interpreted by worker as a reason to trigger a graceful shutdown. This is nontraditional behavior and as such should be warned about.
Changed `i.logger.Info` to `i.logger.Warn` in `cli.signalHandler`.
I haven't tested this. What could possibly go wrong?
> Warn when shutdown signal received

- backend/fake.go
- package_test.go
- processor.go
- processor_test.go
- step_check_cancellation.go
- step_run_script.go
- step_start_instance.go
- step_update_state.go
to avoid racy issues with the job context being done.
State updates failing due to job-level context cancellation, such as happens at job timeout.  This change applies both to AMQP jobs, which we've seen appear to be running past the hard timeout, and to HTTP jobs, which we've seen running past when the `Finish` state update should be complete.
Use the processor-scope context instead so that we can still prevent resource leakage while also ensuring state updates can be sent.
Tests pass, so deploying to staging!
> Use processor context in "Finish" state update

- backend/docker.go
- backend/docker_test.go
https://github.com/travis-pro/team-blue/issues/760
It is currently not easy to determine from the logs which image was used for a docker build, as opposed to GCE builds, which explicitly specify if garnet, amethyst or connie was used.
Included the image name as part of the instace information for docker builds as well. 
Since we were already using tags for this information, I decided to use the tag that included the stack-name (e.g. `travisci/ci-garnet:packer-1505167479`) instead of the language tag (e.g. `travis:ruby`) which was most frequently used.
* The updated unit-tests exhibit the correct behaviour
* Run it locally or in staging and check the instance information in the build logs
>  Use the stack-name as image-name in containers instead of the language tag

- backend/docker.go
- backend/docker_test.go
because attempting to remove them results in brokenness because we don't
create any links egad! :sweat_smile:
Also, set a container name with some meaning in it.
Closes #381 
Explicitly set `RemoveLinks: false` in the container removal config since the attempted link removal is breaking and we don't (shouldn't!) need to remove links that we never created.
I folded in a different container naming here because I _thought_ it was related, but in the end it seems not to be.  Is the container naming sufficiently informative?
> Do not attempt to remove links on container delete

- processor_test.go
Needed for #385 
Test failure due to data race.
Inject the values as func params instead of direct references to get around the race.
The tests!
> Remove local var data race from processor test

- backend/docker.go
- backend/docker_test.go
Required for #385
Generated hostnames that exceed 64 characters result in an oci-level error inside docker, which is Not Good :tm:.
Enforce some limits to keep the generated container name and hostname at 64 chars and below.
Deploy + test on AWS staging
Is allotting 10 chars for job id sufficient?
> Ensure container hostname does not exceed length limit

- CHANGELOG.md
Reducing the size of the Unreleased delta.
(prepare for) cutting a release!  [v3.0.2...v3.1.0](https://github.com/travis-ci/worker/compare/v3.0.2...HEAD)
> Prepare for v3.1.0 release

- CHANGELOG.md
plus a li'l env var update in a previous changelog entry.
The recent addition of bind-mounted volume support in the docker backend is missing from the changelog :scream_cat:.
Add it!
:eyes:
> Add changelog entry for docker backend binds support

- CHANGELOG.md
- backend/gce.go
- cli.go
We need the ability to filter instances by site in order to correctly route alerts in stackdriver to the correct webhook endpoint.
This patch allows the site to be specified via an env var, it will be attached as a network tag to all job VMs.
We can deploy it to staging and check a newly booted instance for its network tags. It should include `testing` and `site-<site>` -- e.g. `site-org`.
> add site tag to gcp provider for instance filtering

- cli.go
Running `travis-worker` inside anything that sends `SIGWINCH` runs the risk of unintentionally triggering a graceful shutdown with toggle pause.
Use `SIGUSR2` instead, since we weren't already using it and it's available.
Run `travis-worker`, send `SIGWINCH`, see it get ignored.
Is `SIGUSR2` OK?
> Switch from SIGWINCH to SIGUSR2 for graceful shutdown + pause

- backend/docker.go
- backend/docker_test.go
- backend/gce.go
- backend/package.go
- backend/package_test.go
Inconsistent hostname generation between the two most-used backends in production.
Use the same hostname generation func in both cases.
The tests + canary deployment in staging.
Should this be applied to other backends where possible?
> Consistently construct GCE and Docker hostnames

- backend/gce.go
this patch is a follow-up to https://github.com/travis-ci/worker/pull/389.
this change was made in order for tag names to be consistent. the naming change is in line with other resources managed by terraform.
> change site tag from site-{org,com} to just {org,com}

- backend/docker.go
- backend/docker_test.go
- backend/package.go
- Container creation fails when a stray container exists with the same name.
- CPUsets aren't getting checked back in when container creation fails.
This combination results in cascading requeues (each time a job is requeued on the same instance, the worker loses track of that CPU set).
- Make worker check for a preexisting container with the same name. If it exists, delete it.
- Check CPU sets back in when container creation fails.
- Add some logging around the above.
Run some jobs. Restart docker while the jobs are running, which should result in `Exited` containers (`docker ps -a`). Logs should show CPU sets being checked back in, and `Exited` containers being deleted.
> Check CPUsets back in if not needed, and be verbose about it.

- CHANGELOG.md
- backend/docker.go
- backend/package.go
- backend/package_test.go
Hostnames that include `_` are not valid and fail to allocate in GCE.
Replace any `_`, as well as replacing multiple `-` with a single `-` so that the generated hostname adheres to the GCE enforced regex of `(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)`.
> Ensure hostname does not contain "_"

- CHANGELOG.md
- README.md
- amqp_job.go
- amqp_job_test.go
- backend/cloudbrain.go
- backend/docker.go
- backend/docker_test.go
- backend/fake.go
- backend/gce.go
- backend/jupiterbrain.go
- backend/local.go
- backend/openstack.go
- backend/package.go
- context/package.go
- script/publish-example-payload
- step_start_instance.go
- step_update_state.go
- step_write_worker_info.go
- step_write_worker_info_test.go
This PR:
* Adds instance ID to StateUpdate metadata. 
* Adds `script/publish-example-payload` to facilitate local development with AMQP.
* Updates README.md.
Addresses https://github.com/travis-pro/gcp-ddos-detector/issues/1
* Added an `instance` field to the `amqpJob` type
* If instance isn't null, copy its ID to the meta field of the body created in `createStateUpdateBody`
`AMQP_URI="amqp://" go test -v . -test.run TestAMQPJob_createStateUpdateBody`
* From the [aj-docker-bits](https://github.com/travis-ci/travis-hub/tree/aj-docker-bits) branch of `travis-hub`, run `docker-compose up`
* Export the environment variables that have been added to the README in this PR
* Run `travis-worker`
* Run `script/publish-example-payload` to add an example queue message
* Run `docker-compose exec …
> Add instance ID to StateUpdate metadata sent to hub

- CHANGELOG.md
- backend/package.go
- backend/package_test.go
Errors coming back from GCE API of `Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'`
Downcase it! :sweat_smile:
> Ensure generated hostnames are lowercase

- backend/docker.go
- backend/docker_test.go
Currently, travis-worker inspects containers every 500 milliseconds, and this is not configurable. This may be contributing to the docker stalls described in https://github.com/travis-pro/team-blue/issues/704.
This PR adds an environment variable `TRAVIS_WORKER_DOCKER_INSPECT_INTERVAL` where this value can be defined (in milliseconds).
`$ go test -v ./backend -test.run InspectInterval`
Set `"debug": true` in `/etc/docker/daemon.json` and run `sudo kill -s SIGHUP $(pidof dockerd)` to reload its configuration.
```
$ make build
$ export TRAVIS_WORKER_DOCKER_INSPECT_INTERVAL=1500
$ travis-worker
```
Enqueue some jobs via the file queue, and observe the duration between container inspections in the docker debug log.
Tell me everything <3
> Add INSPECT_INTERVAL to customize the duration between container inspections

- CHANGELOG.md
- backend/docker.go
There's no easy way to track down all containers currently running for a given repo on worker instances.
This PR adds 3 labels to containers run by worker: repo, job ID, and dist.
This will allow us to filter running containers by label:
```
$ docker ps --filter "label=travis.repo=soulshake/autoscale-tester"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS               NAMES
241af0b720b9        74e2c8c6197c        "/sbin/init"        2 seconds ago       Up Less than a second   22/tcp              travis-job-soulshake-autoscale-test-623773
```
Run worker locally, feed it some jobs, then:
```
$ docker ps --format "table {{.ID}}\t{{.Labels}}"
CONTAINER ID        LABELS
3c5089e0a1e5 …
```
> Add container labels for job id, repo and dist.

- CHANGELOG.md
- http_job_queue.go
The intervals used in the job polling loop and job claim refresh loop are tunable, but ideal values remain TBD.  Changing worker configuration is very disruptive.
Use polling and refresh claim intervals returned in responses from job-board, if present.  See https://github.com/travis-ci/job-board/pull/76.
> Use polling and refresh claim intervals from response if present

- backend/docker.go
- backend/docker_test.go
as advertised in the help text, but not currently true
The help text claims that setting `CPUS` to 0 will disable cpuset allocation, but this is not currently true.
Do like the help text claims.
> Disable docker cpuset allocation when CPUS is 0

- CHANGELOG.md
The size of [this diff](https://github.com/travis-ci/worker/compare/v3.3.1...HEAD).
Prepare for v3.4.0 release given changes and additions beyond a patch level bump and no breaking changes to public APIs.
> Prepare for v3.4.0 release

- script/http-job-test
I've noticed that the integration tests fail every now and then with:
```Error response from daemon: No such container: job-board-redis``` ([example job](https://travis-ci.org/travis-ci/worker/jobs/335990272))
We should try to avoid flakiness in tests as much as possible.
I thought that by trying to run this container first, it will be available by the time we actually need it, thus preventing the failures.
Keep an eye on the integration tests randomly failing here?!
I **think** this should be enough for now and we can resort to introducing more checks (like blocking until the container is up) if this keeps happening. However, there's nothing stopping us from doing that now.
> Run job-board-redis container earlier to prevent test from intermittently failing

- amqp_canceller_test.go
- amqp_job.go
- amqp_job_queue.go
- amqp_job_test.go
- amqp_log_writer.go
- amqp_log_writer_test.go
- amqp_test.go
We have had high CPU alerts for our CloudAMQP Rabbit cluster daily for the last week, and our CPU use has been quite high for over a month. 
CloudAMQP support suggested that this might be due to channel churn and after some investigation, it turned out that we were creating/closing a channel for each job state update message and one channel per job to send the logs. 
We've decided to take the same approach to channel-use as we already had for the build job queue, which implies having the amqp_job_queue create one channel for each queue and have it reused by the processor. 
⚠️ **This is currently running in production in GCE for `production-1-worker-org-c-3-gce` `(IP: 104.197.196.167)`.**
Deploy it and check the AMQP logs for channel created/closed events?!
This has behaved well on EC2 …
> Restructure the use of RabbitMQ channels for logs and state updates

- CHANGELOG.md
Since we have changed the way worker interacts with RabbitMQ a bit in https://github.com/travis-ci/worker/pull/433, we should also bump the worker version in order to better keep track of things.
> Prepare for worker v3.5.0 release

- CHANGELOG.md
- backend/gce.go
- processor_test.go
Instances brought up in GCE without public IPs cannot be easily identified for the purpose of routing traffic via GCE routes.
If no public IP is meant to be allocated, ensure the instance has a `no-ip` tag that may be used for routing traffic through NAT instances.
See https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/jobs/712278
Noting:
``` bash
$ dig +short nat-staging-1.gce-us-central1.travisci.net
35.202.1.222
35.224.132.181
35.225.134.118
35.226.210.51
```
> GCE no-ip tagging

- script/http-job-test
http-job-test is still failing quite often at the stage where it's trying to create the new db, but can't connect to postgres (example: https://travis-ci.org/travis-ci/worker/builds/342690250)
I thought using pg_isready would be a better way to check for postgres' status, but it seems we're still trying to connect a bit too fast (result: https://travis-ci.org/travis-ci/worker/builds/342718822).
I've decided to keep using it for the check (instead of the previous `psql -l`) since I feel it communicates the intention better.
Adding an extra sleep (as ugly as it is) between the check and the createdb call seems to improve things (haven't had any failures yet, but we can also considering increasing the duration if they start occurring again)
Check the builds for intermittent failures.
> Waiting before running createdb fixes flaky integration test

- backend/docker.go
Docker containers are currently labeled with the repo and job ID. When viewing a list of all containers, it would be easier to associate a container with a specific instance if it were also labeled with its IP and instance ID.
This PR makes travis-worker add these two new labels to job containers.
Run on staging with `travisci/worker:v3.5.0-9-g4e46c72` as the docker worker image.
Before:
```
aj@bastion-shared-1:~$ ./all-jobs.sh 
travis-job-soulshake-autoscale-test-713036  4 minutes ago       soulshake/autoscale-tester
travis-job-soulshake-autoscale-test-713040  4 minutes ago       soulshake/autoscale-tester
travis-job-soulshake-autoscale-test-713041  4 minutes ago       soulshake/autoscale-tester
```
After:
```
aj@bastion-shared-1:~$ ./all-jobs.sh …
```
> More docker container labels (ipv4, instance id)

- CHANGELOG.md
- backend/docker.go
The current labels assigned for ip address and instance ID depend on the existence of the "Travis run dir", which is a concept that doesn't appear elsewhere in the worker source code.
Assign container labels via a configurable map instead so that we can add this metadata explicitly into the worker config and aren't coupled to file paths that happen to be used in the hosted infrastructure.  This will mean that we can alter the labels without altering source code, and Enterprise customers can make use of the extra labels without adding files in specific locations.
Tests passing + probably some staging deployments.
> Rework Docker container labeling to allow for arbitrary input via config

- .travis.yml
- vendor/manifest
The current release is built on go 1.9.2 with dependencies last updated Nov 30, 2017.
Build against go 1.9.4 (latest stable) and update dependencies via `gvt update -all`.
> Build on go 1.9.4 with latest dependencies

- CHANGELOG.md
[Delta size of "Unreleased"](https://github.com/travis-ci/worker/compare/v3.5.0...meat-v3.6.0-prep).
Bump to v3.6.0 given non-breaking additions since v3.5.0.
Staging deployments, and maybe production canary deployments:
> Prep for v3.6.0 release

- amqp_job.go
- amqp_job_queue.go
- cli.go
- http_job_queue.go
- multi_source_job_queue.go
- processor.go
- step_start_instance.go
https://github.com/travis-ci/reliability/issues/6
Since we now have a [honeycomb dataset for worker](https://ui.honeycomb.io/travis-ci/datasets/worker), which is based on the logs, we should keep the information in the logs easily searchable and filterable. 
As described in the [issue](https://github.com/travis-ci/reliability/issues/6), this is meant to:
- report instance boot time in seconds (so it's easier to parse by honeycomb, which currently treats it as a string)
- adds the  job id and repository slug to some events that are logged using the processors context (like canceling and requeueing)
- tracks how long it takes for a processor to perform a graceful shutdown
> Improve worker logs

- Dockerfile
- systemd-wrapper
- systemd.service
The current docker image does not include files that are used by [`tfw extract`](https://github.com/travis-ci/tfw/blob/3722ebb1edee7dce3958f1fc83917329188cf364/tfw#L302-L356).
Create the necessary files or copy from elsewhere, and ensure they are copied into the final docker image at the expected path.
> Fill in tfw-ized app compat bits

- script/send-docker-hub-trigger
When someone who does not have push access to the repo submits a pull request, the secret env vars are not set (specifically `DOCKER_HUB_TRIGGER_URL`). Thus this script exits with an exit code `1`, failing the build. We saw this in travis-ci/worker#452.
Since the trigger does not even run for pull requests, that check can be moved further up, before the check for the existence of the secret env var.
> make send-docker-hub-trigger friendly to third-party pull requests

- backend/gce.go
Prevent a VM from being restarted and accumulating cost if Compute Engine wants to restart it (this is for Compute Engine-initiated restarts, not user-initiated ones). This also prevents any startup script code from being run, I can't quite remember what all is in there.
See [the Compute Engine docs](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert#body.request_body.FIELDS.inlinedField_66) for more info about this flag (link may get out of date in the future, search for `resource.scheduling.automaticRestart` on that page if it doesn't go there automatically).
I set the supported API flag, since this is a built-in feature in Compute Engine it seems good to use that.
Unsure if there's a good way to test this, or if it's needed. It's a very small change adding a …
> backend/gce: disable automatic restart

- .travis.yml
- Makefile
- backend/docker_test.go
The travis build was failing for worker.
* Run the linter after the dependencies were fetched, since it was complaining about them missing
* Check for `EOF` instead of `nil` for archive/tar errors (as suggested by the [doc](https://golang.org/pkg/archive/tar/#Reader.Read))
* Make the build and test output less verbose, since it was very hard to figure out what's going on when the log was 7500 lines.
> Fix worker build

- .travis.yml
- cli.go
- config/config.go
- config/config_test.go
- logs_queue.go
Reference issue: https://github.com/travis-ci/reliability/issues/90
This is the first step in separating the logs behaviour in general and allowing worker to use a separate RabbitMQ cluster for build log processing. 
For now, the worker just connects to a new AMQP server if given the option. 
I intentionally chose to create a new interface instead of reusing the LogWriter one in order to keep the current behaviour and transition the responsibility gradually. 
For now, this only applies to AMQP queues (and not the HTTP or file types), but in the future it should be easy to switch between queue types separately for jobs and logs.
> Add the concept of a separate LogsQueue 

- cli.go
- config/config.go
https://github.com/travis-ci/reliability/issues/114
Set hearbeats to 0 in order to disable them (just for the insecure connections, for testing purposes - if this works, will add the same for the amqp tls connection as well).
Check for normal behaviour on staging.
Deploy to a few instances and see if errors like `[ERROR] closing AMQP connection <0.22954.214> (35.188.132.197:38448 -> 10.50.94.192:5671): missed heartbeats from client, timeout: 10s
` stops appearing in the cloud amqp logs
> Make heartbeat configurable for AMQP connections

- amqp_job_queue.go
- cli.go
- config/config.go
defaulting to 0, which is the same as the RabbitMQ default.
My intent here is to ensure that given a travis-worker process with priority `> 0`, that it will be fully utilized prior to other travis-worker processes with `priority == 0`, e.g.:
- `travis-worker` `0` on lower-cost reserved capacity: `priority = 1`
- `travis-worker` `1` on higher-cost dynamic capacity: `priority = 0` (unset)
> Add support for setting RabbitMQ consumer priority

- amqp_job.go
- amqp_job_queue.go
- amqp_log_writer.go
- amqp_log_writer_test.go
- cli.go
- config/config.go
https://github.com/travis-ci/reliability/issues/125
I tried to follow the instructions from the [README of the plugin](https://github.com/rabbitmq/rabbitmq-sharding).
I've declared a new exchange (`reporting.jobs.logs_sharded`, to match what the [changes in the logs app](https://github.com/travis-ci/travis-logs/pull/181) expected and made sure the `LogWriter` routes to the correct exchange based on whether the new config option `TRAVIS_WORKER_RABBITMQ_SHARDING` is set or not.
In terms of manual changes, I had to enable the RabbitMQ sharding plugin in the CloudAMQP Plugins tab and create a new policy (`logs-sharding`) for the sharded exchage, as specified in the README that's linked above.
(Naming could probably be improved, since I was mostly interested in getting this in a state where I …
> Enable the use of the RabbitMQ sharding plugin for travis-logs

- processor.go
- step_update_state.go
- step_upload_script.go
so that we can query for these intervals and see if/how they change based on various load(s).  AFAIK these intervals are not currently directly recorded anywhere, and instead we have to derive the values from multiple metrics/records.  My intent here is to remove that indirection so that exploratory querying in tools like Honeycomb is more accessible to everyone, such as by filtering on `self = step_upload_script` with `P90(since_processed_ms)` (??)
> Add log entries measuring since processed

- CHANGELOG.md
- README.md
- backend/docker.go
- image/api_selector.go
- image/env_selector.go
- image/env_selector_test.go
Image selection in the Docker backend is currently limited to tag-based and api-based strategies, which means that the only "local" strategy (tag-based) will only allow for selection based on `language`, which means that multiple distro images cannot be used in the same Docker API.
Add support for env-based image selection.
The env-based image selector itself is well-tested.  Testing this in a canary deployment would be nice, too!
> Add support for env-based image selection to Docker backend

- CHANGELOG.md
- backend/gce.go
Sudo-enabled job VMs are shutting down unexpectedly due to host maintenance events. (https://github.com/travis-ci/travis-ci/issues/4924#issuecomment-408327917)
According to https://github.com/travis-ci/worker/commit/811106032d78b3bff03434ed431e3ac90542781d, migrating on host maintenance is problematic when GPUs are involved.
This PR sets host maintenance action based on the presence of at least one GPU.
What's the actual problem caused by migrating when GPUs are present? Is there a way we can make migration work?
> Only terminate on host maintenance when GPUs are involved

- job.go
- step_download_trace.go
This ensures a much stricter opt-in and should allow us to turn off tracing at the scheduler-level completely. That will enable us to perform a safer rollout of this feature.
https://github.com/travis-ci/reliability/issues/152
> only run trace code when trace flag is set on job

- backend/jupiterbrain.go
We want to be able to experiment with alternate VM configurations for the Mac infra by changing the CPU count and RAM amount.
Added two new config options for the Jupiter Brain provider:
- `IMAGE_CPUS`: Number of CPUs to give the VM
- `IMAGE_RAM`: MB of RAM to give the VM
If the options are present, they get sent along to Jupiter Brain which will reconfigure the VM appropriately. If they are absent, the request to JB is just as it used to be.
Deployed this worker version to staging in pod-1 and ran some jobs. Looked at the VMs in vSphere and saw the correct configuration for the VMs. Builds also ran substantially faster than those in pod-2 which was unchanged.
Are there places where I should add tests? Does this overall approach seem okay?
> Add config options for jupiter-brain VM config

- CHANGELOG.md
- amqp_job.go
- http_job.go
When a downstream app such as hub gets the state update, it may want to initiate trace processing only if the job actually had tracing enabled.
We don't currently store that data anywhere, it exists transiently in the job payload generated by scheduler. That is why it needs to be propagated through -- there is no place to look it up.
The trace flag is passed through as part of the state update message.
End-to-end test, ideally with [build-trace-processor](https://github.com/travis-ci/build-trace-processor).
refs https://github.com/travis-ci/reliability/issues/153
> propagate trace flag to hub

- amqp_job.go
- amqp_log_writer.go
- amqp_log_writer_factory.go
- amqp_log_writer_test.go
- file_log_writer.go
- http_log_writer.go
- log_writer.go
- package_test.go
- step_update_state.go
- step_write_worker_info_test.go
This one was a bit tricky.
We want to measure "time to first log line" as observed by the user. Since we now have some early log output from worker itself, we need to track where the job execution starts. We can then tack some information to the log part to let downstream (travis-logs) know what is going on.
So that travis-logs doesn't have to go fetch queued_at from the database, we pass that through. We only include it for the first job execution log part though, since log parts are very high volume and we don't want to bloat them.
refs https://github.com/travis-ci/reliability/issues/140
> measure log processing SLI

- .travis.yml
- Dockerfile
- version.go
- The output of the deb and rpm packaging steps *should not* be in use anymore.
- Each job step is under ~10m and a significant portion of that is repeated per job and cannot be reasonably cached.
- Remove the package building, verification, and publishing steps.
- Collapse remaining jobs into a single job.
> Collapse travis jobs, remove packaging step, report golang version

- processor.go
Custom job timeouts are being ignored after the changes introduced in https://github.com/travis-ci/worker/pull/492
Use the hardtimeout in the jobs start attributes instead of the processor one (which just relies on config)
✅ tested on staging
> Take into account custom job timeouts when running script

- CHANGELOG.md
- cli.go
- config/config.go
When running worker without librato configured, e.g. locally or on enterprise, we will print some metrics to the console once per minute. This output tends to be quite spammy, and doesn't make for a very nice out-of-the-box experience.
It's possible to opt-out of that behaviour by specifying:
```
TRAVIS_WORKER_SILENCE_METRICS=true
```
This patch is intended to make the default experience more user friendly by changing the behaviour to an opt-in `TRAVIS_WORKER_LOG_METRICS` flag.
This came out of a conversation with @schultyy about how these defaults have caused some issues on enterprise.
> introduce log-metrics flag, change log metrics to opt-in

- backend/progresser.go
- backend/start_attributes.go
- cli.go
- config/config.go
- processor.go
- processor_pool.go
- step_start_instance.go
The reporting of text-based progress is not something that's generally wanted by product-focused humans at Travis.
Allow for opt-in configuration of text progress, defaulting to no progress.
> Allow for process-level progress type config

- CHANGELOG.md
- amqp_job.go
- amqp_log_writer.go
- amqp_log_writer_factory.go
- amqp_log_writer_test.go
- cli.go
- config/config.go
- file_log_writer.go
- http_log_writer.go
- job.go
- log_writer.go
- package_test.go
- processor.go
- processor_pool.go
- step_update_state.go
- step_write_worker_info_test.go
Passing the infra config through got quite messy unfortunately. I have a feeling that the job config stuff could be simplified a great deal. Instead of Config => ProcessorPoolConfig => ProcessorPool => ProcessorConfig => Processor, we could just pass the original config all the way through.
In any case, the main goal of this is to be able to get per-infra "time to first log line" metrics. To do that, we need to pass metadata to travis-logs. I'm also passing the repo slug, since it might be nice to do more high-cardinality analysis in honeycomb.
refs https://github.com/travis-ci/reliability/issues/190
> propagate job-specific metadata on first log line event

- CHANGELOG.md
- cli.go
- processor.go
- processor_pool.go
- processor_test.go
This has been kind of a long-standing issue for adding config values, as they always need to be added in many places. Most recently encountered as part of https://github.com/travis-ci/worker/pull/508. This patch tries to simplify things by passing the config struct directly.
vaguely refs travis-ci/reliability#190
> pass-through config instead of duplicating the keys all over the place

- backend/jupiterbrain.go
We want to be able to use build tracing on the Mac infra, just like the other infras.
I copied the code from GCE, since both infras just use an SSH connection.
We could deploy it to staging and run a job with tracing enabled.
Did I miss anything?
> Implement downloading traces for Jupiter Brain

- cli.go
- config/config.go
- processor.go
- vendor/manifest
refs https://github.com/travis-ci/reliability/issues/141
MVP worker trace with exporter and root span. 
Let's  do a first iteration on task/subtask execution & latency on our worker instances ⏲ 
We've already implemented trace in /gcloud-cleanup using opencensus go and the stackdriver exporter, so repeating here. 
Running worker locally.  
We want to be backend agnostic, so:
Ok to put everything in global (rather than provider) config? 
#TODO
Link the associated PRs in terraform and config keychain.
> Worker Trace - Opencensus and Stackdriver 

- step_check_cancellation.go
- step_download_trace.go
- step_generate_script.go
- step_open_log_writer.go
- step_run_script.go
- step_send_received.go
- step_sleep.go
- step_start_instance.go
- step_subscribe_cancellation.go
- step_transform_build_json.go
- step_update_state.go
- step_upload_script.go
- step_write_worker_info.go
- step_write_worker_info_test.go
We merged a stackdriver trace prototype in #512 with a root span that started in `(*Processor).process`
This is a 2nd iteration that adds child spans to all steps added in that func to measure latency in this part of the worker (processor) run. 
ProcessorRun is at the heart of the execution actions in worker.  We wanted to start there. 
Tested locally running worker on staging.  The incremental addition of each child span in the steps can be seen here 
Child spans added have been scoped to [this block of code](https://github.com/travis-ci/worker/blob/master/processor.go#L212-L247) in their individual `step_*` files, including cleanup where applicable.  Are there additional places I should be adding child spans in these files? Omissions?
> Worker trace: child spans for all steps in ProcessorRun root span

- .travis.yml
- Makefile
- image/api_selector.go
- image/api_selector_test.go
- script/smoke
Builds take a long time, currently up to 15 minutes.
Try and split out parts into jobs that can run in parallel. Here is the breakdown from build tracing:
That's what this pull request is for!
> attempt to speed up build

- CHANGELOG.md
- processor.go
- step_check_cancellation.go
Refs https://github.com/travis-ci/reliability/issues/198
Follow up to #512 #516.  Once this is deployed to production, we want to be able to do filter queries in stackdriver based on infra/site, repo, or job_id. 
Since we'll be doing other root spans in https://github.com/travis-ci/reliability/issues/199 that will need different attributes, I didn't want to declare attributes globally for all root spans, kept it to where the root span is declared. 
Running worker locally. You'll get these in the stackdriver console.
As we add more root spans, does it makes sense to have a top-level attribute declaration to omit duplication?  Other?
> Opencensus trace span attributes to Processor.Process.Run root span

- processor.go
Tiny follow-up to https://github.com/travis-ci/worker/pull/522.
> move context.WithTimings before root span creation

- CHANGELOG.md
- amqp_job.go
- backend/gce.go
- ratelimit/ratelimit.go
- ratelimit/ratelimit_test.go
Refs https://github.com/travis-ci/reliability/issues/199
See the steps and latency of things in our 
* backend/gce infra, including GCEAPI rate limiting
* redis rate limiting
Extension of  #516 
Running worker locally and viewing the traces on stackdriver staging project.  An example of an expanded trace is [here](https://console.cloud.google.com/traces/traces?project=travis-staging-1&organizationId=928883094116&q=%2Bapp:worker&tid=dbc795f7d2ec1089f71e12b013ec2c3c&start=1539812529379&end=1539816129379)
what expanded traces would be useful, what would be noise? 
I tried to trace http requests in image.makeImageRequest in `api_selector.go` , but ran into some problems.
> Expand set of traced functions (ratelimit, backend/gce, GCEapi)

- backend/gce.go
This should allow us to tell what the SSH dial attempts are failing with during `boot_poll_ssh`.
It would be interesting to see if it is networking in general, or something SSH specific.
> backend/gce: annotate trace with ssh attempt error

- CHANGELOG.md
- processor.go
This will allow us to see time-to-ssh grouped by image in honeycomb, which should help figure out if there is any image-specific correlation for outliers.
> processor: log image name in job finished summary

- CHANGELOG.md
- backend/cloudbrain.go
- backend/docker.go
- backend/gce.go
- backend/jupiterbrain.go
- backend/openstack.go
- image/api_selector.go
- image/api_selector_test.go
- image/env_selector.go
- image/env_selector_test.go
- image/selector.go
- ratelimit/ratelimit.go
refs: https://github.com/travis-ci/reliability/issues/199
This is the last of items of interest to trace in worker, namely:
* any latency in http calls to job-board for /image package and selector interface. 
This is a[ staging trace](https://console.cloud.google.com/traces/traces?project=travis-staging-1&authuser=1&organizationId=928883094116&q=%2Bapp:worker&start=1540820511990&end=1540824111990&tid=a456089ccad2eb79bbf2b3e94ef27fe1) ran on this branch 
De we haz all the interesting bits we want to trace now?
> Worker trace v3: /backend/*{all}, image/selector

- CHANGELOG.md
- backend/gce.go
Refs: https://github.com/travis-ci/reliability/issues/199
by passing in context through the client
similarly to what was done for gcloud-cleanup
https://github.com/travis-ci/gcloud-cleanup/pull/44
Capture traces for GCE api calls. 
Pass in context through the existing client. 
See yourself a trace with GCE api calls [here](https://console.cloud.google.com/traces/traces?project=travis-staging-1&authuser=1&organizationId=928883094116&q=%2Bapp:worker&tid=4e1824e8e932906b21da2552a14c906f)!
> backend/gce: trace calls to google cloud API

- CHANGELOG.md
- backend/docker.go
This is to support http proxies in enterprise, in collaboration with @schultyy.
Setting an environment variable on the docker container. In the long-term, it would probably be better to put this kind of logic into `travis-build` (especially to make this work across infras), but from what I've heard it is currently easier to roll out a newer version of worker on enterprise than travis-build.
So that's what we're going with for now.
I'm testing it with a local worker. We can also test it with our enterprise test installation.
It can be tested by setting the environment variable:
```
export TRAVIS_WORKER_DOCKER_HTTP_PROXY=http://proxy:80880
```
That should make the `http_proxy` and `HTTP_PROXY` env vars set in the container.
> introduce http_proxy variable in docker container

- CHANGELOG.md
- backend/docker.go
In addition to `HTTP_PROXY`, we now also support: `HTTPS_PROXY`, `FTP_PROXY`, `NO_PROXY`. This is specifically needed for an enterprise customer.
These can be configured via:
```
export TRAVIS_WORKER_DOCKER_API_VERSION=1.37
export TRAVIS_WORKER_DOCKER_HTTP_PROXY=...
export TRAVIS_WORKER_DOCKER_HTTPS_PROXY=...
export TRAVIS_WORKER_DOCKER_FTP_PROXY=...
export TRAVIS_WORKER_DOCKER_NO_PROXY=...
```
Follow-up to https://github.com/travis-ci/worker/pull/537
> backend/docker: support for additional env vars HTTPS_PROXY, FTP_PROXY, NO_PROXY

- CHANGELOG.md
- backend/gce.go
The goal is to get a better idea of how many calls we are actually sending to the API, since the GCE quotas page only gives us 5 minute averages, and we'll want to know more about the peaks.
> backend/gce: track metric for rate of calls to gce api

- CHANGELOG.md
- backend/gce.go
Refs https://github.com/travis-ci/reliability/issues/199
Even though we have sleep times as constants during a job run, we don't have any indication of how many times those sleeps are called as a result of retries.  This adds them to worker trace to give us that data. 
Passing in context to `time.Sleep` calls in the same manner as https://github.com/travis-ci/worker/pull/528, so that we don't orphan any outside of the Processor.Run 
Staging worker with time.Sleep spans added [here](https://console.cloud.google.com/traces/traces?project=travis-staging-1&tid=ba1e9379f01be950fb19af218ee8c549&start=1541075763880&end=1541079363880&q=ProcessorRun) 
I'm not entirely sure if this is the way I should be doing this, I simply followed patterns and this is the only thing that compiled. 😅
> backend:gce opencensus trace- add time.Sleep calls to processor.Run root span

- CHANGELOG.md
- backend/gce.go
passing context through a var declaration with the same name as the parent in a loop results in grandchildren-of-children without being tied to their parents.
This weird rendering of a loop child span [here](https://console.cloud.google.com/traces/traces?organizationId=928883094116&project=eco-emissary-99515&tid=0257f175c9cf5650c303e8fc4af246fd&q=%2Bapp:worker&start=1541430390845&end=1541433990845)
use a blank identifier to ignore a new context declaration. 
ran a worker in staging, this fixes the span rendering. ✅
> Do not override context in existing child

- CHANGELOG.md
- amqp_job.go
- file_job.go
- http_job.go
- job.go
- package_test.go
- processor.go
- step_check_cancellation.go
- step_generate_script.go
- step_open_log_writer.go
- step_run_script.go
- step_start_instance.go
- step_upload_script.go
The goal of this is to make it easier to correlate per-job stats with errors. e.g. how does "context deadline exceeded" correlate with how long steps are taking. Where is the time for those errors being spent?
Since honeycomb does not have joins (and it would be impractical due to the sampling anyway), we need to propagate some of this information back up to the top level event.
> processor: include final error in "finished job" log message

- CHANGELOG.md
- step_download_trace.go
- step_generate_script.go
- step_run_script.go
- step_start_instance.go
- step_upload_script.go
This allows us to see if a step failed in stackdriver, and see what exactly the error was.
> trace: add return code for steps

- CHANGELOG.md
- backend/gce.go
- cli.go
We've been seeing some orphaned spans during worker boot. This ties them together:
The patch also removes an instance deletion that happens in `gce.go`. That really should be done via `StartInstance.Cleanup`. If there are any cases in which `StartInstance.Cleanup` does not properly delete the instance, I'd love to understand those. But from what I can tell, it should always take care of things.
> trace: trace CLI.Setup and avoid orphaned spans during worker boot

- backend/gce.go
- step_run_script.go
The build trace isn't saved in case of timeouts or log maxsize errors.
Continuing to the download trace step instead of `ActionHalt` when we encounter these errors.
Will test on staging.
> Make sure we still save the build trace after RunScript errors

- CHANGELOG.md
- backend/gce.go
This is so that we can get a decent estimate of the API quota we need in practice.
> track rate of gce api calls we would make (if it were not for rate limiting)

- CHANGELOG.md
- backend/docker.go
- backend/jupiterbrain.go
- backend/package.go
- remote/package.go
- ssh/package.go
- winrm/package.go
value is generally signed 16-bit int, can be negative.
vaguely refs https://github.com/travis-ci/reliability/issues/196.
> store exit code in int32 instead of uint8

- CHANGELOG.md
- backend/gce.go
We can see the number of api calls made by worker for a sample job in stackdriver trace:
Since we're hitting some GCE API rate limiting troubles, it would be good to reduce the number of calls per job.
It turns out that two of the calls can be cached. The image select and the machine type. That saves us two calls per job.
This patch does just that. This will hopefully reduce our GCE API traffic by 20-30%. 🤞
> backend/gce: cache gce api calls for image and machine type, reduce total api call volume

- CHANGELOG.md
- backend/gce.go
VMs from warmer often don't get deleted because the worker ends up looking in the wrong zone when trying to delete them.
Passing back the zone information from warmer and then using that in the gce worker backend for the deletion.
Turn worker back on, see if it's able to delete instances this time
How GOod is my Go code?
> Adding zone information when using warmed instances

- amqp_job.go
- processor.go
This allows hub (a downstream consumer) distinguish between job runs, which allows us to better handle certain races around state updates during requeue storms.
refs travis-ci/reliability#222
> processor: generate per-job UUID to distinguish between job runs

- CHANGELOG.md
- backend/gce.go
- ratelimit/ratelimit.go
- ratelimit/ratelimit_test.go
In order to be able to adjust our rate limiting on the fly it would be good to be able to dynamically configure it through redis.
This allows the values to be changed without deploying or restarting worker. This will allow us to slowly approach our API quotas.
The main risk is increased traffic to redis. I think redis should be able to handle a couple hundred requests per second easily though. So I'm not too worried. In the worst case we can cache the config value in memory though and update it every couple seconds (maybe using something like [go-cache](https://github.com/patrickmn/go-cache)).
To enable in worker (terraform-config):
```
TRAVIS_WORKER_GCE_RATE_LIMIT_DYNAMIC_CONFIG=true
```
To set the values in redis:
```
trvs redis-cli travis-production REDIS_URL mset …
```
> ratelimit: dynamic configuration of `max_calls` and `duration` via redis

- CHANGELOG.md
- backend/gce.go
There is a mismatch between attempted and actual GCE calls. I would expect the attempted ones to be higher, but that is often not the case. For example:
refs https://github.com/travis-ci/reliability/issues/222
> backend/gce: add missing rate limit calls

- CHANGELOG.md
- ratelimit/ratelimit.go
Looking at a trace, there is some unaccounted time spent in the rate limiter. One possible explanation for that would be contention on the redis connection pool.
This extra span should help validate that theory.
refs https://github.com/travis-ci/reliability/issues/222
> ratelimit: trace redis connection pool checkout

- cli.go
- config/config.go
- http_api.go
- processor.go
- processor_pool.go
- remote_controller.go
To run worker correctly in Kubernetes, we need to be able to control rollouts of new instances of worker such that the pool size doesn't exceed our computing capacity for running CI jobs. We're writing a Kubernetes controller for that, but to do its job, worker needs to have API for controlling the pool size. Some of that was present in the existing HTTP API, but it was missing some important things.
* Refactored HTTP API to use a Gorilla mux and have its own struct with the API handlers
* Changed the API URLs, methods, and format to be more resource-oriented and use JSON for easier use by other software
* Added API to ProcessorPool to set the size of the processor pool, instead of only being able to increment and decrement
* Firmed up the contract around `ProcessorPool.Size()`: it now …
> Make worker pool size manageable by software

- processor_pool.go
This addresses an edge case in the behavior added in #566 where if a worker is waiting for its first processor to start, a graceful shutdown request will never proceed.
When we receive a graceful shutdown request, attempt to close the channel waiting for the first processor. Essentially this is pretending a processor was started, so we stop waiting for it and proceed as normal.
It's pretty to produce the behavior by starting worker with POOL_SIZE=0 and sending it a SIGINT (or deleting the pod in Kubernetes). The process should die quickly, rather than wait indefinitely.
Any.
> Allow graceful shutdown when no processors were started

- processor_pool.go
The RemoteController API can receive multiple requests to update the worker pool size at the same time. This causes an issue where we start many more processors than we expect because they aren't added to the list of processors synchronously. Instead they are added in a goroutine.
Move the creation of the Processor out of the goroutine, so that it happens synchronously with the call to Incr. This alone isn't enough, because now Incr needed to use the processorsLock synchronously, which would not work for SetSize, which wants to do all of its Incr/Decr calls in one block of the lock.
For that, I introduced private versions of Incr and Decr that assume the lock is already locked, and use those in several places. Incr and Decr just delegate to their private versions now once they've taken …
> Fix ProcessorPool.SetSize to be more atomic

- processor_pool.go
- remote_controller.go
Sometimes the worker operator makes requests to the HTTP API before the processor pool has started. This causes a crash because some properties of the ProcessorPool are not set until it's running.
Add a ready check endpoint to the API which checks the pool for its readiness. We'll define a readiness probe for worker pods in Kubernetes so that the pod will not be considered ready until this check passes. It makes sense that the worker pod as a whole wouldn't be ready until the processor pool is up and running.
Test in staging with the worker-operator.
Any.
> Add ready check endpoint for remote controller

- CHANGELOG.md
- backend/gce.go
if instance is not "zone-pinned" such as with vm config override(s).
> Retry instance insert in alternate zone on error

- CHANGELOG.md
- backend/gce.go
- backend/gce_test.go
The most common errors that currently result in requeues are exacerbated by immediately requeueing.
Wrap each interaction with the GCE API in retry with exponential backoff so that problems such as Rate Limit Exceeded may be immediately mitigated instead of requeuing and possibly hitting the same error.
Canary deploy(s) probably?
Is this awful? Non-awful?
> GCE requeue resilience

- step_run_script.go
A broken link to our docs, where the link doesn't send users to the right anchor due to case-sensitiveness :)
See:
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received (working)
vs
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> Fix docs links for timeouted job

- .travis.yml
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"
> .travis.yml: The ‘sudo’ Tag is now deprecated

- .snapcraft.yaml
- .snapcraft/daemon.start
Make it easy to install the worker on any architecture and in a reproducible way.
Ship it as a snap package so it can be installed on any distribution and any architecture.
Install the snap, configure it and join it to the staging CI environment.
> snapcraft: Add initial snap packaging

- Makefile
> Makefile: Install golint before running gometalinter

- config/provider_config.go
The GCE provider uses an ACCOUNT_JSON variable to fetch the credentials
for accessing the GCE API. This variable can either be a path to the
JSON or a string of the JSON. A similar implementation is used in
gcloud-cleanup.
In worker, the provider config is processed and all config variables are
'unescaped' as if it was a URL. This causes the JSON to become unusable,
mainly because the private key contains `+` symbols which get replaced
by spaces.
This solution simply checks if the key ends with ACCOUNT_JSON and skips
the 'unescape' step. This ensures backwards compatibility for any other
variables relying on this behavior. Ideally we should only run this step
when required, as in 'variable is a URL that needs unescaping'.
I've done a local run of the code with the .env config from …
> Don't unescape ACCOUNT_JSON variable

- backend/lxd.go
This sets a whole bunch of bunch of additional options and exposes some new settings:
- Sets quota on Docker volume
- Give us more rounded uid/gid allocation (easier to debug in `ps`)
- Make main storage pool name configurable
- Disable /dev/lxd access
- Enable syscall interception (now disabled by default)
- Enable MAC, IPv4 and IPv6 network filtering
> Update for current LXD features

- backend/lxd.go
> lxd: ipv4.address isn't CIDR

- README.md
Hello,
The `Uninstalling` readme section is confusing since `travis-worker-uninstall` script [was deleted](https://github.com/travis-ci/worker/commit/25d33b75e71ee623877636788f52935e709becb7).
I believe that it makes sense to just remove this section.
Read the README and see whether it's misleading.
It would be nice to see any feedback.
Best regards!
> Remove Uninstalling section from README

- backend/docker.go
- backend/package.go
- backend/package_test.go
Builds which uses services can not start via systemctl because of some profile permission issue in docker.
`System has not been booted with systemd as init system (PID 1). Can't operate.`
Solution requires to have support to set following envs:
`TRAVIS_WORKER_DOCKER_BINDS`
`TRAVIS_WORKER_DOCKER_SECURITY_OPT`
`TRAVIS_WORKER_DOCKER_TMPFS_MAP`
Issue is related to Travis CI Enterprise docker solution.
Internal ticket:
https://travisci.assembla.com/spaces/Enterprise/tickets/realtime_cardwall?ticket=37
Solution based on information from https://github.com/defn/docker-systemd
Install worker with bionic support for Travis CI Enterprise docker solution.
https://docs.travis-ci.com/user/enterprise/setting-up-travis-ci-enterprise/
> Services start support on Bionic for TCI Enterprise in docker

- go.mod
- go.sum
```
go: github.com/flosch/pongo2@v0.0.0-20190505152737-8914e1cf9164 requires
github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1
go get -t -d ./github.com/travis-ci/worker/...
Failed to run 'go get -t -d ./github.com/travis-ci/worker/...' for 'travis-worker': Exited with code 1.
Verify that the part is using the correct parameters and try again.
```
Use `replace` directive
Run a build on snapcraft
> Try to sort out deps issues

- .snapcraft.yaml
With the latest go version 1.13 build is falling we have to use 1.12.
https://build.snapcraft.io/user/DamianSzymanski/worker
> Use go 1.12, build failed with latest stable go

- backend/lxd.go
The latest version of lxd fails with an error "Failed to get volume ID for project", lxd team added the possibility for the project name to be encoded into the volume name in the format `<project>_<volume>`. In this case we can't use underscore.
https://github.com/lxc/lxd/commit/d14390bfabc5500b0e84a1786608e828a2117e21#diff-0f4206d46c1d5de5381d7418858eb10bR33
Use dash instead of the underscore.
Run travis worker with lxd backend
any
> Don't use underscore in storage volume name

- backend/gce.go
We need to be able to set a list of zones where it is allowed to start instances (instead of single zone, as it is now)
Added a `TRAVIS_WORKER_GCE_ZONES` config
Deploy to staging
> Implement random zone picking

- .snapcraft.yaml
When running worker under snap the remote interface is unable to bind to the network
Allow `network-bind`
Deploy and test
> [Snap] Allow worker to bind to network

- backend/gce.go
We want to have bigger disk size for windows OS, but keep it the same for other OS
Add a separate config `DISK_SIZE_WINDOWS` config that overrides `DISK_SIZE` only for windows OS
Deploy to staging
> Allow to set custom disk size for windows

- .snapcraft.yaml
golang 1.13 and 1.14 will both fail with different errors when
attempting `go get` commands.  Since full support of go.mod is
not yet available in snapcraft 3.9 (stable), this commit will
disable go modules until it can be enabled (v3.10+). Modules
are disabled by setting GO111MODULE=off in the build environment.
The current yaml specifies the go version in `build-snaps`.  However,
the go plugin has a property `go-channel` which sets the go snap
version.   The default value is `latest/stable` which is currently
go 1.13.  If a different version is specified in `build-snaps`, the
go snap will be updated/overridden to the version (implicitly) specified
by the `go-channel`.  An example log snippet shows this behavior:
```
<snip>
go (1.12/stable) 1.12.17 from Michael Hudson-Doyle (mwhudson) …
```
> snapcraft: fix build using golang 1.13+

- backend/ec2.go
Sometimes worker was starting instance, crashing and then starting the same instance again. 
thanks to @pavel-d
> Fix for multiple vm's started by worker

- amqp_canceller.go
- canceller.go
- canceller_test.go
- http_job_queue.go
- processor_test.go
- step_check_cancellation.go
- step_run_script.go
- step_subscribe_cancellation.go
When job is terminated due to insufficient credit balance, a log entry about jobs being terminated due to insufficient credits balance must be printed to job log
Pass a "reason" in the command payload
Send a cancelation message with a reason in the payload
> Write optional job cancellation reason to job log

- amqp_job.go
- amqp_job_queue.go
- backend/ec2.go
- backend/gce.go
- backend/start_attributes.go
- job.go
This PR introduces the worker to spin up a vm defined in the config provided by the user in their `travis.yml` file
> added vm_size parameter for setting instance size from amqp (#646)

- amqp_job_queue.go
when providing an unsupported json config (like 'arch' matrix on tcie-2.2
or 'dist' matrix') two ACK were sent causing worker to die ( first one from job loop, second from 'Finish')
> removed double ACK on json parse error

- backend/lxd.go
Fix sudo warning. That line is executed before travis-build can configure /etc/hosts and stuff.
> Fix sudo warning

- backend/lxd.go
In LXD backend, the PROCESS environment variable is assigned to the wrong golang variable (`limitNetwork` instead of `limitProcess`). This causes abnormal behavior in the worker when trying to change the default LXD process limit.
On travis-worker installed via snap (` v6.2.16+git30.2798f7f`), adding `export TRAVIS_WORKER_LXD_PROCESS="1000"` causes the `limitNetwork` property of LXD to change, instead of changing `limitProcess`:
```
limitNetwork:\"1000\", limitProcess:\"5000\"
```
---
On a travis-worker binary built from source with the necessary fix in place, adding `export TRAVIS_WORKER_LXD_PROCESS="1000"` applies the change to the right property i.e `limitProcess`:
```
limitNetwork:\"1Gbit\", limitProcess:\"1000\"
```
Assigned it to the correct variable.
- Clone this repo and and make …
> Fix wrong assignment of PROCESS environment variable 

- backend/gce.go
- image/api_selector.go
- image/params.go
Worker will pass one more query param named "gpu_vm_type" to job-board which is needed for selection of image for GPU.
I added the gpu_vm_type param in api_selector.go class where the rest of the params (like tags, is_default, repo etc) are passed to the POST `/images/search` request. Its only meant for GCE so the GpuVmType info is only passed from ace.go to api_selector.gce.
deployed on staging
none
> Add gpu to query tags
