cmd/travis-worker/main.go, lib/backend/docker.go, lib/backend/fake.go, lib/backend/jupiterbrain.go, lib/backend/package.go, lib/backend/sauce_labs.go, lib/job.go, lib/job_queue.go, lib/step_run_script.go, lib/step_update_state.go
plus a bunch of switching to pointers for memory $aving$
=> Add support for linux and language images to jupiter brain backend

lib/backend/docker.go, lib/backend/fake.go, lib/backend/jupiterbrain.go, lib/backend/package.go, lib/backend/sauce_labs.go, lib/step_run_script.go
for clarity, debugging help, support support, warm fuzzies
=> Add the instance "ID" to the "Using worker:" line in logs

.gitignore, .travis.yml, Makefile, utils/pkg/includes/common, utils/pkg/pkg_build, utils/pkg/pkg_run, utils/pkg/pkg_test, utils/pkg/templates/default_env_travis_enterprise, utils/pkg/templates/default_env_travis_worker, utils/pkg/templates/post_install.sh, utils/pkg/templates/pre_remove.sh, utils/pkg/templates/systemd_travis_worker.service, utils/pkg/templates/upstart_travis_worker.conf
- Builds packages using fpm
- Tests the installation of each package with docker
- Using `dist: trusty`
- Uploads packages to packagecloud.io/travisci/worker/
=> Add packaging to builds

.codeclimate.yml, src/github.com/travis-ci/worker/amqp_job.go, src/github.com/travis-ci/worker/cmd/travis-worker/main.go, src/github.com/travis-ci/worker/job_queue.go, src/github.com/travis-ci/worker/step_run_script.go
For https://github.com/travis-pro/team-blue/issues/160
=> New installer script for Enterprise

.gitignore, Vagrantfile, utils/installer/installer.sh
- Includes Vagrantfile
- For https://github.com/travis-pro/team-blue/issues/160
=> Install script for travis-worker, for enterprise setups.

utils/installer/installer.sh
Install latest version unless a version is provided to the installer script
=> Install latest version unless a version is provided to the installer script

.gitignore, utils/pkg/includes/common, utils/pkg/pkg_build, utils/pkg/pkg_run
https://github.com/travis-pro/team-blue/issues/171
=> Adding support to publish non-release builds to `worker-testing` apt repository

src/github.com/travis-ci/worker/backend/gce.go
Some changes fixing some issues I noticed, and also getting rid of all linter issues. Explanations in the commit messages for some things.
=> GCE backend fixes

src/github.com/travis-ci/worker/amqp_job.go, src/github.com/travis-ci/worker/cmd/travis-worker/main.go
After working on #43 I decided to look through the "high cyclomatic complexity" and "duplicated code" warnings to see if there's any one of them that should be changed, and found these two spots that had parts that seemed like they would make sense to improve.
=> Some cleanup / refactorings

.travis.yml, src/github.com/travis-ci/worker/test/log_integration_test.go, src/github.com/travis-ci/worker/test/package.go
It works on my machine™, at least.
Maybe :soon: some more integration tests too :smile_cat:
=> Fix integration tests

utils/installer/installer.sh
- Switched default docker daemon storage driver to aufs
- Add docker commang to tag `travis:ruby` as `travis:default`
=> Switch to aufs, tag ruby as default

utils/pkg/templates/upstart_travis_worker.conf
unlimited respawn but with a 5 second sleep on exit
=> some tweaks to the upstart script template

src/github.com/travis-ci/worker/backend/jupiterbrain.go
I _think_ this might be what is causing our goroutine leak. Looking at a gouritine dump I see 209 goroutines still running `session.Run("bash ~/wrappser.sh")`, and I think these are left over from cancellations.
=> backend/jupiterbrain: clean up SSH connection in case of cancellation

src/github.com/travis-ci/worker/step_generate_script.go
There has been a few network-related errors in the past, which with the current code is handled as unrecoverable errors. Now, if the error is unknown (i.e. not a `BuildScriptGeneratorError`), we requeue the job for running again later.
=> step/generate-script: requeue job on unknown error

src/github.com/travis-ci/worker/backend/bluebox.go, src/github.com/travis-ci/worker/backend/docker.go, src/github.com/travis-ci/worker/backend/gce.go, src/github.com/travis-ci/worker/backend/jupiterbrain.go, src/github.com/travis-ci/worker/config/help.go
Provider help entires are now a map instead of one monolithic static string with formatting.
=> Added map-based provider help generation.

src/github.com/travis-ci/worker/backend/jupiterbrain.go
so that gaps in availability do not result in massive waves of requeues.
=> Add exponential backoff to all jupiter brain HTTP reqs

.travis.yml, src/github.com/travis-ci/worker/backend/gce.go, src/github.com/travis-ci/worker/help.go
as well as ensure the help output is deterministic.
=> Add auto-imploding capability to GCE backend provider

src/github.com/travis-ci/worker/backend/jupiterbrain.go
By default we're using the env image selector, since this is equivalent to the old selector, making this backwards compatible.
=> backend/jupiter-brain: add support for image selectors

src/github.com/travis-ci/worker/backend/docker.go, src/github.com/travis-ci/worker/backend/docker_test.go
=> @jacobgreenleaf's fix for docker backend wrt HostConfig :heart_eyes_cat:

amqp_job.go
This helps hub in being able to process messages that arrive out of order.
=> Send all known timestamps to hub

backend/docker.go
I'm not 100% sure on the way this is documented, but couldn't find a better wording. Suggestions welcome!
=> docker: Add some documentation on how to disable resource allocation

backend/gce.go, backend/gce_test.go, backend/package.go
by using the script upload retries to do the job
=> Switch to poll SSH instead of API for inst ready

.travis.yml, CHANGELOG.md
=> Prepare changelog for v2.0.0 release

backend/gce.go
to (theoretically) further reduce API usage
<del>**NOTE**: I'm not thrilled about this implementation</del>
=> Add exponential backoff & optional skip to GCE instance stop

cli.go, processor.go
Includes the ID of the last job the processor worked on and its current status (new/processing/waiting).
=> sigusr1: print more info

backend/gce.go, backend/gce_test.go
rather than reading it as config
=> Generate SSH key pair in GCE

backend/jupiterbrain.go
for display in worker info header
=> Ensure jupiterbrain `BaseImage` string is set

backend/backend.go, backend/docker.go, backend/docker_test.go, backend/fake.go, backend/gce.go, backend/gce_test.go, backend/jupiterbrain.go, backend/local.go, backend/package_test.go, cli.go, cmd/travis-worker/main.go, config/config.go, config/config_test.go, config/provider_config.go, help.go, image/env_selector.go, image/env_selector_test.go, package_test.go, processor_test.go, step_open_log_writer_test.go, utils/smoke
These changes caused the worker to no longer pick up configuration from the environment, blocking further work from the master branch. Reverting it for now, until we can put further work into figuring out what is
causing this.
This reverts commit 9155f0ddb5e8f4ac880409a5165e39717d19b75d, reversing changes made to 9b768f50cf20f47a876aba91c61aa280d401feec.
The original PR adding this was #153.
=> Revert "Merge pull request #153 from travis-ci/meat-cli-unify"

README.md, backend/package.go, cmd/travis-worker/main.go, config/config.go, context/package.go, doc.go, image/doc.go, processor.go, ratelimit/ratelimit.go
This doesn't touch any code, but adds more Godoc docs and updates the README a bit.
=> Add more docs

backend/gce.go, cmd/travis-worker/main.go, config/config_test.go, vendor/manifest
=> Add support for private IPs on GCE

README.md, cli.go, cmd/travis-worker/main.go, config/config.go, config/config_test.go, help.go, vendor/manifest, version.go
from github.com/codegangsta/cli :arrow_right: gopkg.in/urfave/cli.v1
=> Migrate imports and vendoring for cli lib

backend/docker.go, backend/docker_test.go, utils/lintall, vendor/manifest
to hopefully:
- work with current stable docker
- work correctly when run on separate host
=> Refresh docker backend

.travis.yml, CHANGELOG.md
including switch to keepachangelog format and bump to go 1.7.1
=> Prepare CHANGELOG.md for v2.4.0 release

backend/cloudbrain_client.go, backend/gce.go, backend/jupiterbrain.go, cli.go, cli_test.go, config/config.go, image/api_selector.go, step_generate_script.go, vendor/manifest
for use with cyclist/whatever remote supervisor-like relationship
=> Implement heartbeat handling

.docker-entrypoint.sh, .travis.yml, Dockerfile, Makefile, utils/docker-push, utils/docker-smoke
over here, as opposed to https://github.com/travis-ci/packer-templates
=> Build and publish alpine docker image

.travis.yml, Dockerfile, cli.go, cli_test.go, config/config.go, package.go, utils/smoke-docker
to work moar better with cyclist and terraform config
=> Hook and heartbeat updates

cli.go, config/config.go, processor.go, processor_pool.go, processor_test.go
=> log-writer: make max log length configurable

utils/smoke-package
=> Verify docker version in smoke test with less strictlyness

cli.go, processor_pool.go
logging the same info during shutdown and USR1 handling.
=> Log processor pool total

amqp_job.go, file_job.go
=> Add a meter for job finish state

Dockerfile
This enable graceful shutdown when you do `docker stop`.
=> Added stop signal to shutdown the worker gracefully

processor.go, step_open_log_writer.go, step_start_log_timer.go
=> processor: set logWriter maxLogLength when creating log writer

backend/docker.go
but allow for setting it via env for testing.
=> Switch default docker exec command back to `bash {script}`

backend/gce.go
Currently we have a single flag `PUBLIC_IP` which controls two things:
* whether build instances receive a public IP
* whether we connect to that public ip or use the private one
It turns out however, that will be wanting to run in a hybrid mode, where instances have a public ip (so that it can talk to the internet without NAT), but no incoming traffic is allowed (dropped via firewall).
So we want to have a public IP, but not connect to it. This PR adds that capability.
=> backend/gce: introduce PUBLIC_IP_CONNECT flag so that we can connect to the private ip from worker

Makefile, backend/cloudbrain.go, backend/docker_test.go, backend/package.go, config/config.go, config/package_test.go, context/package_test.go, errors/errors.go, http_job.go, http_log_writer.go, metrics/package_test.go, ssh/package.go, step_run_script.go, step_start_instance.go
This includes some minor-ish style fixes and dead code removal as reported by various linters in `gometalinter`. See the commit messages for more information on the various steps.
=> Linter fixes

CHANGELOG.md
Diff: https://github.com/travis-ci/worker/compare/v2.7.0...eb138f934e4ddad9b0a7271c9acbb03302241bc6
=> Add v2.8.0 changelog entry

CHANGELOG.md
=> Backfill changelog entry for vagrant updates

CHANGELOG.md, Makefile, amqp_canceller_test.go, amqp_job.go, amqp_job_test.go, amqp_log_writer_test.go, amqp_test.go
This addresses a regression found when upgrading from v2.5.x.
=> Ensure AMQP job "finished_at" is included when available

amqp_canceller.go, amqp_job.go, amqp_job_queue.go, amqp_log_writer.go, backend/cloudbrain.go, backend/docker.go, backend/gce.go, backend/jupiterbrain.go, cli.go, cli_test.go, file_job.go, file_job_queue.go, http_job.go, http_job_queue.go, http_log_writer.go, multi_source_job_queue.go, processor.go, processor_pool.go, step_generate_script.go, step_open_log_writer.go, step_run_script.go, step_send_received.go, step_start_instance.go, step_update_state.go, step_upload_script.go
for ease of correlation, grokking
=> Include a "self" string in internal log records

CHANGELOG.md, backend/docker.go, backend/gce.go, backend/jupiterbrain.go, backend/start_attributes.go
as well as using the image name given via StartAttributes if available, as will
be the case for jobs delivered via
[job-board](https://github.com/travis-ci/job-board).
=> Add optional API-based image selection to Docker backend

CHANGELOG.md, bin/travis-worker-install, ssh/package.go, utils/smoke-package
**Update**: addressed change in docker APT repo and available versions
=> Set HostKeyCallback on ssh.ClientConfig

CHANGELOG.md, build_script_generator.go, cli.go, http_job.go, http_job_queue.go, http_log_part_sink.go
plus some logging tweaks while working on job-board integration
=> Fix backoff and body closing for some HTTP things

CHANGELOG.md
plus make some changelog formatting a bit more consistent
=> Prep for v2.9.2 release

amqp_job.go, amqp_log_writer.go, backend/cloudbrain.go, backend/docker.go, backend/gce.go, backend/jupiterbrain.go, cli.go, cli_test.go, context/package.go, file_job.go, file_job_queue.go, http_job.go, http_job_queue.go, http_log_part_sink.go, http_log_writer.go, multi_source_job_queue.go, package_test.go, processor_pool.go, sentry_logrus_hook.go, step_send_received.go, step_start_instance.go, step_update_state.go, vendor/manifest
for ease of copy-pasta tracing + switch to new repo name for
github.com/sirupsen/logrus
=> Include "job_path" log entry if available

CHANGELOG.md, cli.go, config/config.go
for performing actions also allowed via signalling.
=> Add a local HTTP API

http_log_part_sink.go
and rebuild the request each retry to ensure the body can be fully read each time.
=> Include `source=worker` in log parts POSTs

ssh/package.go
1. This PR is to support login to newly booted up VM with a key but without a passphrase.
2. Tested the changes with Openstack backend.
=> Adds support to allow ssh with a key but without a passphrase

CHANGELOG.md
=> Prepare for v3.0.1 release

.travis.yml, backend/docker_test.go, bin/travis-worker-install, packaging/functions.bash, script/clean, script/package, script/smoke-package
`make test` results in a few test failures due to unquoted variables.
I quoted the variables 
`make test`
=> Fix shellcheck warnings in bin/travis-worker-install

amqp_job.go
as it is a suspected contributing factor to general unhappiness with AMQP jobs.
We have been seeing heightened AMQP-related errors on all infrastructures since rolling out v3.0.2.
Mostly rolling back [this change](https://github.com/travis-ci/worker/commit/778e285192fc755891afbf5d59c0776758c26db5#diff-624c34b5b2d559c68f7bb49e2653436d) to return to a state update method implementation that was working well for ~2 years.
Staging rollout tests.
=> Back out the amqp state update timeout cleverness

backend/docker.go
This commit adds a new function to enable setting
bindings between the host where Docker runs and
the container image which is launched for building
purposes.
According Docker documentation: "...when you use a
bind mount, a file or directory on the host machine
is mounted into a container. The file or directory is
referenced by its full or relative path on the host
machine...[1]"
With this approach users can set multiple bindings
by exporting the environment variable
TRAVIS_WORKER_DOCKER_BINDS and associating the
bindings separated by spaces:
export TRAVIS_WORKER_DOCKER_BINDS='/var/run/docker.sock:/var/run/docker.sock /home:/home'
When launching travis-worker, this configuration will be mapped as
host_config="&docker.HostConfig{Binds:[]string{"/var/run/docker.sock:/var/run/docker.sock", …
=>     Add a new option to set binding when using Docker as backend.

CHANGELOG.md, backend/docker.go, backend/docker_test.go
=> Switch from dotty to dashy container hostname

.travis.yml, CHANGELOG.md
The size of [this delta](https://github.com/travis-ci/worker/compare/v3.1.0...HEAD).
Cut a release!  I chose v3.2.0 given the added features and lack of breaking public API changes.
👀
=> Prepare for v3.2.0 release

CHANGELOG.md
=> Prepare for v3.2.2 release

CHANGELOG.md, backend/gce.go
defaulting to the previous behavior of prefix+uuid.
Some kinks need to be worked out with the deterministic hostname, so rather than fully backing it out ...
What's another config bit?
=> Make deterministic hostname configurable in GCE

CHANGELOG.md
The size of [this delta](https://github.com/travis-ci/worker/compare/v3.2.2...HEAD).
Cut a release v3.3.0 because of additions and changes that don't break public APIs.
Tests plus staging testing ✔️
=> Prepare changelog for v3.3.0

CHANGELOG.md, step_open_log_writer.go, step_run_script.go, step_start_instance.go, step_upload_script.go
Mildly inconsistent logging around requeue conditions, as well as requiring investigation beyond log line for relevant configuration values.
Add more logging, consistently, including relevant configuration values in log entry.
=> Improve logging around requeue conditions

CHANGELOG.md
Inconsistent/missing logging around requeue conditions in production.
Address the inconsistencies and open this PR for cutting a release!
=> Prepare for v3.3.1 release

.travis.yml, backend/docker.go, vendor/manifest
Outdated dependencies and outdated Go version.
Update Go and update dependencies and fix the parts that broke when updating dependencies.
Tests + staging deploy(s)
=> Update dependencies and Go version

processor_test.go
Flaky test is flaky!
Wait longer.
It's _self-testing_ :boom:.
=> Increase timeouts in flaky processor test

vendor/manifest
Outdated dependencies.
`gvt update -all` because it is good!
Should we tag and release prior to merging this?
=> Update all dependencies

.travis.yml, bin/travis-worker-install, packaging/functions.bash, script/lintall, script/package
Builds are currently failing for the master branch.
Fix the things shellcheck was complaining about according to the suggestions in the test failures and https://github.com/koalaman/shellcheck/wiki/SC2207.
Is the build green again? 😬
=> Fix shellcheck errors

README.md
Adds notice about a missing dependency that needs to be installed on the developer's machine
=> shellcheck needs to be installed

README.md
Update the release process, per @meatballhat suggestion in https://github.com/travis-pro/manual/pull/671#discussion_r168768865
=> Add more details about our current release process

backend/docker.go
=> CONTAINER_LABELS should be space-delimited, not comma-delimited

config/config.go
Potentially addresses https://github.com/travis-ci/job-board/issues/78
https://github.com/travis-ci/job-board/issues/78
data correction
deploy worker in staging, and see what happens with a non-existring `dist` key
yes, any.
=> Change default dist to trusty

CHANGELOG.md, LICENSE, README.md, script/docker-push
The size of [this delta](https://github.com/travis-ci/worker/compare/v3.6.0...HEAD) is greater than zero.
Prep for a v3.7.0 release!
=> Prepare for v3.7.0 release

CHANGELOG.md
=> add github diff link for v3.8.0 to CHANGELOG

CHANGELOG.md
Tiny release bump to account for the AMQP changes. 😄
=> Prepare v3.8.1 release

CHANGELOG.md
I thought the addition of logs sharding warrants a new release, so I updated the changelog accordingly.
=> Prepare for 3.9.0 release

backend/cloudbrain.go, backend/docker.go, backend/fake.go, backend/gce.go, backend/jupiterbrain.go, backend/local.go, backend/openstack.go, backend/package.go, backend/progresser.go, backend/text_progresser.go, backend/text_progresser_test.go, package.go, step_start_instance.go, step_upload_script.go, step_write_worker_info.go
with implementations for backend/gce and backend/jupiterbrain
[![asciicast](https://asciinema.org/a/mZH50reCXOkyhjf8c2B8LSjmL.png)](https://asciinema.org/a/mZH50reCXOkyhjf8c2B8LSjmL)
=> Implement optional instance startup & upload progress reporting

backend/backend.go, backend/cloudbrain.go, backend/docker.go, backend/fake.go, backend/jupiterbrain.go, backend/local.go, backend/openstack.go, ssh/package.go, step_download_trace.go
refs travis-ci/reliability#152
=> improve logging around buildsh-trace

backend/gce.go
...and if it is set to true, then `OnHostMaintenance` should be `TERMINATE`.
`TRAVIS_WORKER_GCE_PREEMPTIBLE` currently defaults to true, and `OnHostMaintenance` behavior currently defaults to `MIGRATE` (to avoid jobs being aborted on GCE maintenance events). Therefore, if `TRAVIS_WORKER_GCE_PREEMPTIBLE` isn't overridden, instance creations fail with the following error:
```
googleapi: Error 400: Invalid value for field 'resource.scheduling.preemptible': 'true'. Scheduling must have preemptible be false when OnHostMaintenance isn't TERMINATE., invalid
```
This PR:
- makes `TRAVIS_WORKER_GCE_PREEMPTIBLE` default to `false`
- if `TRAVIS_WORKER_GCE_PREEMPTIBLE` is set to true and `onHostMaintenace` is set to `MIGRATE` (which is the case by default for non-GPU VMs), the latter is overridden by …
=> TRAVIS_WORKER_GCE_PREEMPTIBLE should be false by default

amqp_job.go
This should allow us to see trends in job duration as seen by worker.
=> log duration of job execution (for honeycomb)

CHANGELOG.md, backend/docker.go, backend/gce.go
refs https://github.com/travis-ci/reliability/issues/151
=> build tracing for docker backend

backend/gce.go
refs https://github.com/travis-pro/incidents/issues/291
=> gce: fix build instance on context timeout

CHANGELOG.md
=> Prepare for version 4.1.2

CHANGELOG.md, backend/gce.go
refs https://github.com/travis-ci/reliability/issues/195
=> warmer: make sure to store instance name and ip from warmer

.travis.yml, CHANGELOG.md, Dockerfile, Makefile, script/clean, vendor/manifest
=> Update all dependencies, build binaries via go 1.11.1

backend/gce.go
https://github.com/travis-ci/reliability/issues/202
Create a new SSH dialer for each instance, which should use the key provided by the warmer service.
✅ Tested on staging, in combination with https://github.com/travis-ci/warmer/pull/4
=> Add SSH support for the warmed instances

backend/gce.go
Follow-up to https://github.com/travis-ci/worker/pull/529, this change didn't make it into that pull request (I forgot to push it...).
refs https://github.com/travis-ci/reliability/issues/204
=> warmer: use public ip when connecting to instance with public ip

backend/fake.go
This is in order to test out the behaviour of the system when worker is constantly erroring (requeue storms).
Sample config:
```
export TRAVIS_WORKER_AMQP_URI=...
export TRAVIS_WORKER_BUILD_API_URI=...
export TRAVIS_WORKER_QUEUE_NAME=builds.standalone
export TRAVIS_WORKER_AMQP_CONSUMER_PRIORITY=1
export TRAVIS_WORKER_POOL_SIZE=50
export TRAVIS_WORKER_PROVIDER_NAME=fake
export TRAVIS_WORKER_FAKE_ERROR=true
```
refs https://github.com/travis-ci/reliability/issues/208
=> backend/fake: introduce option to error out all jobs

CHANGELOG.md
Shipping `HTTP_PROXY` support for an enterprise customer.
=> prepare v4.6.0 release

CHANGELOG.md
=> Worker release 4.6.2

CHANGELOG.md
=> prepare v5.0.0 release

backend/gce.go
This is a fix for https://github.com/travis-ci/worker/pull/558. `refreshInstance()` was changing the zone from the short form `us-central1-a` to the full URL form `https://www.googleapis.com/compute/v1/projects/travis-staging-1/zones/us-central1-a`. Which is why deletions were failing in the non-warmer flow.
=> backend/gce: fix zone name after refreshInstance()

CHANGELOG.md
refs https://github.com/travis-ci/reliability/issues/222
=> Prepare v5.1.0 release

processor_pool.go, remote_controller.go
It's hard to tell what kinds of requests the worker is responding to when it makes pool size changes because of the remote controller.
Log the requests!
Run it in staging.
Any.
=> Add logging for the remote controller

CHANGELOG.md
=> Prepare for v6.0.0 release

backend/gce.go, backend/openstack.go
=> gofmt: Make gofmt happy

backend/lxd.go
=> lxd: Load overlay module

backend/lxd.go
=> lxd: Handle non-managed bridges

backend/lxd.go
=> lxd: Get existing subnet as CIDR

backend/lxd.go
=> lxd: Setup docker cache if present

backend/lxd.go
=> lxd: Don't return halfway through setup

amqp_job_queue.go, backend/lxd.go, backend/start_attributes.go, backend/start_attributes_test.go, cli.go, config/config.go, config/config_test.go, file_job_queue.go, http_job_queue.go, job_test.go
PR adds image selector based on api and env to lxd provider and arch attribute to the defaults
=> lxd: Add image selector and arch attribute to the defaults

backend/lxd.go
PR adds support for xenial OS on lxd backend, add static ip using network interface configuration
Add static ip using network interface configuration, write configuration to /etc/network/interfaces, netplan is available from bionic
Start worker with lxd backend and xenial base image
=> Add support for xenial network interface configuration

image/api_selector.go
Sometimes it's useful to know what image was returned by job board and what was the request
Add debug log
Deploy and check logs
=> Add debug log for image selector api

.snapcraft.yaml, .travis.yml, Makefile, backend/docker_test.go, backend/lxd.go, cli.go, config/config.go, go.mod, help.go, http_job_queue_test.go, image/api_selector.go, image/api_selector_test.go, image/manager.go, script/http-job-test, script/http-job-test-internal
Worker doesn't download missing LXC images automatically
It should download and import an image, if it doesn't exist locally
:shipit:
=> Automatically download LXC images if they are not present on host

.snapcraft.yaml, backend/lxd.go, cli.go, go.mod, go.sum, image/manager.go
It's not possible to execute `lxc` binary for images import due to snap packages confinement
Use LXD REST API and custom images server
Deploy to staging
=> Use LXD REST API for images import

backend/lxd.go
IPv6 filtering is hardcoded
Make IPv6 filtering configurable and add `TRAVIS_WORKED_LXD_NETWORK_IPV6_FILTERING` env var, with default value set to `true`
Deploy and set the env var to `false`
=> [LXD] Make IPv6 filtering configurable

backend/lxd.go
Signed-off-by: Rafael Peria de Sene <rpsene@br.ibm.com>
Allow setting security.privileged when running a LXD container via worker.env by setting 
export TRAVIS_WORKER_LXD_SECURITY_PRIVILEGED="true", false is the default.
When running, it will set it properly:
```
config:
image.description: Travis CI Ubuntu 18.04 Full build env template!
limits.cpu.allowance: 300%
limits.memory: 6GB
limits.processes: "5000"
linux.kernel_modules: overlay
security.devlxd: "false"
security.idmap.isolated: "true"
security.idmap.size: "100000"
security.nesting: "true"
security.privileged: "true"
```
Add a new variable that makes it option, default is false.
Set it to true and when doing a Travis build running in a LXD, get the configuration of the running container. This preference should be there.
A review is …
=> Add an option to define security.privileged

.snapcraft.yaml, .travis.yml, Dockerfile
=> Update go 1.13.x -> 1.14.x

backend/ec2.go
ORIGINAL PR BY j[onhenrik13](https://github.com/jonhenrik13) [here](https://github.com/travis-ci/worker/pull/587)
This PR Contains 10 of 12 commits from original as 2 of them was "merge from master" commits.
**What is the problem that this PR is trying to fix?**
Adding ec2 backend provider code in order to run builds in EC2
**What approach did you choose and why?**
I adapted the docker code to use EC2 api
**How can you test this?**
By setting TRAVIS_WORKER_PROVIDER_NAME='ec2'
**What feedback would you like, if any?**
I'd like feedback in the pr.
=> Ec2 provider

backend/lxd.go
=> Fix sudo warnings

amqp_job.go, amqp_job_queue.go, backend/ec2.go, backend/gce.go, backend/start_attributes.go, job.go
Adds possibility to setup instance size from AMQP
=> added vm_size parameter for setting instance size from amqp

go.mod, go.sum
updated packages basing on trivy scan result
=> security updates

.travis.yml, backend/docker_test.go
fixed .travis.yml after updates
=> Ga 1 17test
